### ISSUE TITLE
transposed Images

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#100]
In "Detector::focalPlaneToPixelCoordinates(double xFPprime, double yFPprime)" (Detector.cpp, ln. 1636) it is stated, that the rows are correspondent to the y value and the cols are correspondent to the x value of the pixel- and subpixel map. 

This leads to the creation of transposed images in the end, because the definition of arma::arrays is the contrary. This causes problems regarding the jitter, which is inverted and/or seen on the wrong axis of an image.

At the moment we just transpose the resulting images, which seems to work.

**Comment by JorisDeRidder** [comment]
Could you clarify why you think that the images are transposed? The x-axis is defined along the serial readout register corresponding to the columns, and the y-axis along the parallel readout varying along the rows. So I don't see any error there.

About the armadillo arrays, internally they are column-major rather than row-major, but since their element access is stil Array[row][column], that shouldn't be a problem either.

How are you visualising the images?  In Python, for example, the imshow() of matplotlib transposes the image as it tries to mimic Matlab. But this is a visualisation issue, rather than a PlatoSim issue.

**Comment by BertoltLang** [comment]
This explains it. We are using python and MatLab for accessing the images and I couldn't figure out for a while, why the jitter seemed to be on the wrong axis. So you are right, this is a visualization problem, but maybe this is helping somebody else with the same problem to save some time.

**Comment by JorisDeRidder** [comment]
It's indeed something that's easily overlooked, so this Issue will surely help others as well.

**Comment by SaraRegibo** [comment]
Clarified in the documentation, in #110 & #111
