### ISSUE TITLE
FCAM Issue

### ISSUE THREAD

**Issue by bowl-sa** [IvS-KULeuven/PlatoSim3#1001]
Hi,

When trying to simulate a star on the FCAM (PlatoSim version 3.6.0-389-g0ef8ae6) I get the error 
`Simulation.run(): PlatoSim returned with exit code -11.
`
It seems to be related to the Telescope Group ID, as the simulation runs fine when I set the Group ID to 'Custom'.  I have attached an archive containing the stellar catalog I am using, the input file, the code and the log file.
[to_github.zip](https://github.com/user-attachments/files/16247780/to_github.zip)

**Comment by nicholasjannsen** [comment]
Dear @bowl-sa 

Please check the log file to see what causes the error? (open the log file and have a look and report back in this chat). If you read the documentation, PlatoSim provides 3 files: a HDF5, a YAML, and a LOG file. Typically the `-11` error are related to input and output writing. In this case I suspect that the error is caused by the fact that you are using the `Custom` group ID. We specifically state in the documentation that for using the F-CAM you need to give `Fast` in that YAML entry. 

Cheers,
Nicholas

**Comment by bowl-sa** [comment]
Hi Nicholas,

I think I've identified the problem. In the master branch, the function createStarCatalogFileFromPixelCoordinates doesn't accept GroupID = 'Fast'. I manually installed the develop branch version of simulation.py and it seems to work.

**Comment by nicholasjannsen** [comment]
Okay good to hear that you solved the issue @bowl-sa. Just for the record, I believe you simply have to set this parameter to the YAML object (`SimFile["Telescope/GroupID"] == "Fast"`) before you request a catalogue creation using the method `simfile.createStarCatalogFileFromPixelCoordinates()`. Did you try that?

**Comment by nicholasjannsen** [comment]
@bowl-sa, did this solve your issue?

**Comment by bowl-sa** [comment]
@nicholasjannsen Yes, I have everything working now.
