### ISSUE TITLE
Cosmics

### ISSUE THREAD

**Issue by dk766** [IvS-KULeuven/PlatoSim3#106]
This is more a question related to the configuration file.

I am trying to simulate CCD images with cosmics (for the CCD image and the smearing + offset lines) but I don't see the configuration for this in the configuration file.  Also I do not see any entry in the Seeds section. 
I remember that this functionality was implemented in a previous version of PlatoSim

Can you pls. help me with some information (and maybe also update the documentation with thie relevant information)

**Comment by JorisDeRidder** [comment]
When going to PlatoSim 3, we removed the implementation of the cosmics. The reason is that it lacked any realism: cosmics were simply implemented as elongated gaussians where the size and elongation were free parameters. In reality, cosmics often do not look like gaussians but can, for example, have a "worm-like" appearance.  We therefore thought that the current implementation would not be useful at all to test any cosmic-removal algorithm, which likely requires a more realistic description.

If you think that the gaussian cosmics can nevertheless be useful, or even better: if you can refer us to a more realistic description of cosmics, we can re-implement it, although likely not before the Christmas holidays.

**Comment by JorisDeRidder** [comment]
I'm going to close this issue, and open a new one where cosmics are an official feature request.
