### ISSUE TITLE
Question about reference frame

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#162]
I am a little bit confused with the reference frame of new PlatoSim. Using my previous simulation file for PLatosim, I got “no star within the Subfield” with new PlatoSim 3.2.

When I look to the new python/refrenceFrames.py file, I am surprise with the values of the heading table : `CCD = \ {    'A'  : {'Nrows': 4510, .....`

I put one star on the CCD B at the FP position (+20mm, +20mm).
Using Platosim referencesFrames.py function and CCD variable value, my star is outside the CCD :
`'B'  : {'Nrows': 4510, 'Ncols': 4510, 'firstRow': 0,    'zeroPointXmm':  -1.0, 'zeroPointYmm': +82.162, 'angle': 3*pi/2},`
  
```
import referenceFrames
import math as m
referenceFrames.focalPlaneToPixelCoordinates(20., 20., 18., -1.0, 82.162, 3*m.pi/2.)
(-1166.666666666667, 5675.666666666667)
```

Using the same value in PIS gives: 
```
import pislib as pis
pis.fp2ccd(20/0.018, 20/0.018, 82.18/0.018, 1/0.018, 90)
(1055.5555555555552, 3454.4444444444453)
```
=> exactly what I was waiting for

It's OK for PIS but values are very strange for Platosim3.2.

Did you change something with the reference frame ?
I usually use the reference frame attached for FP to CCD coordinates conversion.

![referenceframe](https://cloud.githubusercontent.com/assets/12544881/26496627/9e35b00a-4228-11e7-823d-19458e39d915.JPG)

**Comment by JorisDeRidder** [comment]
The table `CCD = \ { 'A' : {'Nrows': 4510, ... ` in referenceFrames.py has indeed changed with respect to the previous version of PlatoSim. After a suggestion by DLR, we changed the order of rotation and translation when transforming from the focal plane to the CCD reference frames. This has the advantage that the zero points in the table are now all the same for each CCD, only the rotation angle differs. 

Concerning the "No star within the subfield" problem, please be aware that the new version of PlatoSim now makes sure that the spacecraft is rotated so that the solar panels face the Sun (in the middle of the time series). This implies of course that the entire focal plane is rotated. Might this be the cause of the discrepancy with PIS?

FYI, I just committed a first version of a PDF file explaining the PlatoSim reference frames in docs/technicalnotes.

**Comment by manugr788** [comment]
OK, I have successfully run Platosim V3.2 with a star at the center of the subfield. I don't clearly understand the new FP reference frame (how every CCD origin could be on the same FP reference point ?) but using the function pixelToFocalPlaneCoordinates everything works fine.

**Comment by JorisDeRidder** [comment]
The fact that every CCD has the same offsets is a consequence (and advantage) of switching the order of rotation and translation when going from FP to CCD coordinates. 

WARNING: as recently remarked by DLR, PlatoSim's CCD nomenclature ('A', 'B', 'C', 'D') does not correspond to the nomenclature used in the payload consortium ('1', '2', '3', '4'). Moreover, the labelling of the CCDs is not done in the same order either (i.e. 'A' does not correspond to '1', 'B' not to '2', etc) . Today we therefore updated the nomenclature of PlatoSim3 (in branch 'alphaRelease') to correspond with what is used in the payload consortium. The new labelling of the CCDs can be found on page 9 of docs/technicalnote/PLATO-KUL-PL-TN-0001.pdf
