### ISSUE TITLE
throughputMap reset?

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#202]
When I start a longer simulation which should include the effects of particulate Contamination and/or molecular Contamination, but without vignetting, polarization and quantum efficiency, the throughputMap is not reset after each exposure. 

(detector.cpp - void Detector::generateThroughputMap() )

This leads to a fade over time, meaning that the first image is fine, but the thousandth image contains no detectable signal anymore. I assume, this isn't intended and suggest, that the line for resetting of the throughputMap is moved up, so that it's no longer under the condition, that vignetting, polarization or quantum efficiency is used.

**Comment by SaraRegibo** [comment]
After investigation, this turns out to be a problem only in the `develop` branch (not in the `master`).  I have moved up the reset of the values of the throughput map to 1.0 up to start of the `generateThroughputMap()` method, so out of the condition of angle-dependent contributions to the throughput map.  Solved in #207.

**Comment by SaraRegibo** [comment]
Assigning to Bertolt for closure.
