### ISSUE TITLE
Number of cosmics too high 

### ISSUE THREAD

**Issue by dk766** [IvS-KULeuven/PlatoSim3#206]
The number of cosmics for the BiasMaps is too high.
Currently for a cosmics impact rate of (10 impacts/cm2/s) I get in a BiasMap of 100x2255 pixels about 65 cosmics which is very close to the expected number if the BiasMap would be affected by cosmics for the entire ExposureTime of 22s. To my understanding though this is not the case since the time that a value from the BiasMap can be affected by cosmics is only in the the readout (which is about 0.75ms) while a pixel on the CCD may be affected for the entire ExposureTime + a part of the readout.

For reference I will quote a discussion between Reza Samadi and Rene Heller on a related subject:

"...there is some confusion made between the offset and the over-scan rows.
While a pixel corresponding to an offset window (2225 pixels) spends only 0.75 ms in the register, a pixel from the over-scan row integrates charges (and accordingly proton impacts) during 3s.
Therefore, if the proton flux is 1000 impacts/s/cm²,
one pixel from the over-scan row will collect in average
1000 * 3 * (18e-4)^2  = 0.01 impact (Note that one pixel = 18 micron meter = 18e-4 cm)
and accordingly 0.29 impact in average for the 30 pixels  of the 30 over-scan rows (for a given column over the 2225 columns).
For the offset window, the 2225 pixels collect in average  1000 * 0.75e-3 * (18e-4)^2 * 2225 = 5.4e-3 impact"

I would suggest a quick inquiry of the CCD WG to clarify this issue and make sure that the PlatoSIm implementation is in sync with the latest specifications of the CCDs used for PLATO

**Comment by SaraRegibo** [comment]
**For the pixel map:**
Cosmics hits strike the image area during exposure and readout, so here we will have to multiply with (integration time + readout time).

**For the smearing map:**
Cosmic hits strike the parallel over-scan (i.e. the smearing map) during readout only, so here we will have to multiply with the readout time.

**For the bias map:**
The pixels in the bias maps are short-lived, as they only exist in the readout register, during its serial readout.  Not only is the number of cosmic hits very small here (as the serial readout happens at 2.94MHz), the effect is also confined to one row in the serial pre-scan (since no charge of the image area is shifted down from the image area).
