### ISSUE TITLE
psf.hdf5 missing from input files

### ISSUE THREAD

**Issue by dbrown-astro** [IvS-KULeuven/PlatoSim3#208]
The psf.hdf5 file seems to have disappeared from the inputfiles directory. This makes it quite difficult to test with the MappedFromFile PSF model. Could you replace the pdf.hdf5 file please?

**Comment by rhuygen** [comment]
The psf.hdf5 file has been moved out of the GitHub area for some time now because of its size. 

From the documentation pages:  If you want to use realistic PSF models instead of a Gaussian, you can download these from [our FTP server](ftp://plato:miSotalP@ftp.ster.kuleuven.be/psf.hdf5). A convenient place to store this file is in the /inputfiles directory.

**Comment by rhuygen** [comment]
The link to the FTP server is ftp://plato:miSotalP@ftp.ster.kuleuven.be/psf.hdf5

**Comment by dbrown-astro** [comment]
Sorry, I must have skipped over that line of the documentation
