### ISSUE TITLE
Segmentation Fault if csv ends with a empty line - Related to #229

### ISSUE THREAD

**Issue by dk766** [IvS-KULeuven/PlatoSim3#233]
Found where was the problem (in my setting) for #229  : in one of the starcatalog files that I was using I had an empty line at the end of the file. 
This generates segmentation fault.
It would be nice to either inform the user that the input file is invalid or simply to deal with this case by ignoring the line.

**Comment by JorisDeRidder** [comment]
I adapted the code so that star catalogs can now contain empty lines or lines only containing whitespace (spaces, tabs, ...). These lines will now be automatically skipped. Although I did test it, I would be grateful if you could verify if your star catalog that used to crash is now working properly. The results are in the latest develop version.

**Comment by dk766** [comment]
I pulled the changes and I confirm the error was fixed. 
I also tried a few combinations (comments spaces etc.) and everything seems ok now. 
Thanks for the quick fix !
