### ISSUE TITLE
Need for better and consistent checking of input file format

### ISSUE THREAD

**Issue by rhuygen** [IvS-KULeuven/PlatoSim3#303]
When reading input files that are specified in the YAML configuration file, we need to implement the following checks:
* does the file exist and is it readable?
* does it have the correct format?

When above checks fail a user friendly message should be printed to the log file and the console, containing
* the filename and full path
* description of the problem
* if possible, location in the YAML input file

**Comment by dk766** [comment]
Please also update the online documentation to correctly indicate the column separators.
The http://ivs-kuleuven.github.io/PlatoSim3/SupplementaryFiles.html#stellarVariability indicates that a comma-separated values are needed.

I would propose to use accept as delimiters/separators a number of characters: space, tab, comma, semi-colon, pipe, slash, backslash etc. The only special characters that cannot be used as separators are "." used in float point numbers and "#" used a comment.

**Comment by JorisDeRidder** [comment]
Thanks for signaling this. The sentence currently reads "The latter files also consist of two comma-separated columns:" while it should read "The latter files consist of two columns, separated by a space:". I will make a separate issue for this.

For the separators, if we accept several characters, we may have to use regular expressions which may slow down reading large ascii files. It would be good to test this first and take this into account in the cost-benefit analysis.

**Comment by dk766** [comment]
Note (as a fellow sw developer): In regards to the input file parsing: since we are talking here about a very simple pattern I usually use my own parser method: 
 - load full file in memory
 - split by lines
 - if line starts with '#' ignore line
 - for each line if you meet a separator - any of them - a new column begins
I believe a basic custom parser like this can be easily implemented without using regexp (which as you say may be slow) and without significant performance costs.

**Comment by rhuygen** [comment]
I'm not in favor of allowing multiple characters for the input files. I vote for a fixed and consistent format and proper documenting that format. It is far easier to change an input file with an external python script than it is in C++.

**Comment by dk766** [comment]
In this case I would propose a CSV (values separated by comma) format since this is a pretty simple and common to most of the application/tools/api can deal with it pretty easily. The whitespaces (at least space and tab) though should be still filtered out. Also comment lines  should be supported. An example of valid input file (spaces and tabs may be present before or after any column or separator) :

```
# Column 1 label, Column 2 label
    #   Additional information 
  1,  4
3.0   , 6
   786723.323,    764.6e4
```
Optionally comments at the end of the line could also be supported (similar to the input.yaml file):
```
   465.0,    764  # comment text
```
