### ISSUE TITLE
Inconsistent sky background value

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#313]
I made a simple simulation but I get an inconsistent value for the sky background. 
The information given in the HD5/skyBackground/ gives me  5816 e-
However, in the image I estimated the background to be around 3075 e-.
My simulation data can be downloaded here https://upload.obspm.fr/get?k=nPwHA16WOSg7exX6yLG

Some information about my system:
PlatoSim 3.3.4 (Master)

gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

cmake version 3.10.2

clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by JorisDeRidder** [comment]
The HDF5/Background/skyBackground/ values is expressed in photons/exposure, not e-/exposure. Note that in PlatoSim, the QE is angle dependent, so the sky background in e- is not constant over the image.

**Comment by SaraRegibo** [comment]
**Sky background [photons / exposure]**
Product of:
* input sky background from the configuration file: 342 photons / pixel / s
* exposure time  from the configuration file: 21s
* transmission efficiency from the configuration file: 0.8162 à 0.7975 (evolves over time)

5852 à 5728 photons / pixel / exposure
→ this is what is written out in `HDF5/Background/skyBackground/values`

**Sky background [e- / exposure] (estimate)**
* input sky background from the configuration file: 342 photons / pixel / s
* exposure time from the configuration file: 21s
* transmission efficiency from the configuration file: 0.8162 à 0.7975 (evolves over time)
* mean quantum efficiency from the configuration file: 0.5985 e- / photons
*  angle dependency of the QE: 1.01 (since there is no further information on the exact angle dependency of the QE, we use a fixed value (for now!), as agreed with Anko)
* efficiency due to polarisation from the configuration file: 0.989
* efficiency due to particulate contamination from the configuration file: 0.972
* efficiency due to molecular contamination from the configuration file: 0.9573

3261 à 3182 e- / pixel / exposure
→ this is what you estimated from the image

**Comment by SaraRegibo** [comment]
@drsamadi Is further action required from our side?  If so, don't hesitate to ask.  If not, could you close the issue, please?

**Comment by drsamadi** [comment]
Thanks for your answers! 
Note that to process the process the data and compute the aperture mask we need to know exactly the level of background in the image (in e-).  
For the time being we have not yet developed the algorithm to derive it from the background windows. 
Therefore, it would be useful to have an estimate given in the HDF5 file. 
In any case for the future in order for us to compare the real value with the one derived from the PLATO algorithms, we need this value . 
For a small imagette, the sky background is not expected to vary across the imagette since it is possible in such case to have a reliable representative value of the background.  
Réza

**Comment by JorisDeRidder** [comment]
OK. I'll make a separate issue to calculate the sky background in e-. We'll think about whether it is best/easiest to compute it for the center of subpixel image, or an average value over the whole subpixel image, or yet another measure.

**Comment by drsamadi** [comment]
I've discovered a problem still regarding the amount of sky background.

In one of my simulation, I measure in the image a sky background of about 2000 e-.
Given my configuration file (here attached), this is consistent, however the contribution of the background flux collected during the frame transfer is missing.
For instance, assume a sky background of 100 e-/s, the amount of background collected during the integration is obviously 2100 e-, but one must also take into account the amount of background collected during the transfer time (4s), accordingly the background should be equal to 
 2500 e-. 
Réza

PlatoSim 3.3.5

[PSMOB-TC-OSC-001-COB_000.yaml.gz](https://github.com/IvS-KULeuven/PlatoSim3/files/2584461/PSMOB-TC-OSC-001-COB_000.yaml.gz)
