### ISSUE TITLE
Noise in PLATOSim

### ISSUE THREAD

**Issue by reneheller** [IvS-KULeuven/PlatoSim3#316]
I'm using the latest PLATOSim version (v3.2.0-RC1-498-ga946238) to simulate an exoplanet transit (with a huge 50% drop in brightness just to simplify a by-eye check). It's an m_V = 10 solar-type star and I do not inject any stellar noise, just a flat out-of-transit light curve. The resulting output shows the transit (yes!) but the noise seems to be too large throughout the light curve.

I see flux variations of ~10% on a time scale of 5,000 seconds (~1.4 hours) and this does not seem to be white noise. It rather seems to be time-correlated systematic noise, i.e. it must come from the telescope/CCD/pointing/thermal expansion etc. I think the magnitude of these effects are much too large.
![screenshot 2018-10-29 at 17 02 21](https://user-images.githubusercontent.com/7735050/47663202-c4ec4600-db9c-11e8-9ac4-fab3344cb551.jpg)

**Comment by JorisDeRidder** [comment]
The variation in the time series depends on the input time series for the platform jitter and the thermoelastic drift + how you did the photometry. What made you conclude that the variation in the time series is inconsistent with the input?

**Comment by rhuygen** [comment]
Hi Rene, I would like to urge you to update and follow the releases of PlatoSim3. You can find the releases at https://github.com/IvS-KULeuven/PlatoSim3/releases.

The reason I ask is that your version number doesn't confirm with a PlatoSim3 version where stellar variability is implemented. That is only in the system since 3.3.0.

**Comment by dk766** [comment]
Here are a few clarifications for the simulation that Rene run:
- the simulator version PlatoSim 3.3.4-34-g60c8a16; the version originally reported was due to a caching issue of the web interface he used. This was now fixed.
- for the photometry we used the PlatoSim provided API.
- jitter settings are the default ones 
- drift settings are default (so disabled)

For more info pls. see the attached config file. If necessary I can also provide the variable source file but I think this is irrelevant for this particular issue/question 
[inputfile.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2528901/inputfile.txt)

**Comment by JorisDeRidder** [comment]
Looking at your yaml inputfile, I noticed you're not using an inputfile for the platform jitter time series, but PlatoSim's internal jitter random walk. The corresponding RMS of the yaw, pitch, and roll in the inputfile is set to a generative 1.0, but the Plato spacecraft will do much better in fact. Can you redo your simulations with JitterYawRms, JitterPitchRms, and JitterRollRms set to 0.05?

**Comment by reneheller** [comment]
I have rerun the simulations (input file attached) with JitterYawRms, JitterPitchRms, and JitterRollRms set to 0.05 as per Joris' recommendation (thanks!). The resulting lightcurve shows that the jitter indeed had a big impact on the noise properties. Now I'm just wondering where my transit has gone... The attached file shows the light curve with the jitter parameters set to 1.0 (red line, my previous run) and 0.05 (blue line, my new run) as well as the model of the stellar variability (black line). The transit does not seem to be in any of the resulting light curves. I will run another simulation with an unrealistic 50% transit depth to see if this is now an issue related to the injected stellar variability (file).

[inputfile.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2529694/inputfile.txt)
![platosim_](https://user-images.githubusercontent.com/7735050/47719412-67630280-dc4b-11e8-9f8a-8715bdb8476f.jpg)

**Comment by JorisDeRidder** [comment]
Hi Rene, are you positive that nothing else has changed (PlatoSim version, inputfiles, ...)? This seems very strange to me, even the y-values of your lightcurve are completely different.

**Comment by reneheller** [comment]
Hey Joris, my apologies – I should've added that the model (black line) is offset by an arbitrary value just for the purpose of illustration. The original light curve was fed into PLATOSim in units of DeltaMag. While the offset is arbirtrary, however, the depth of the transits are what I would expect to see in the simulated light curves. I will redo the transit injection with a much deeper transit to see if the error is on the injection part. I'l keep you posted...

**Comment by reneheller** [comment]
I've redone a couple of transit injections and the issue of too shallow a transit depth persists. I'm attaching a plot that shows my injected model (black line) of a 3 Jupiter radius planet transiting a solar radius star. The expected transit depth is (3 R_Jup / R_sun)^2 ~ 0.089 = 8.9%. Indeed, the transit depth in the model curve is (1e6 - 8.95e5) / 1e6 = 0.105 = 10.5%. This "measured" value is a little higher because of the stellar limb darkening, that's alright. The PLATOSim output (blue curve), however, has a transit depth of (1.01e6-1e6) / 1.01e6 ~ 0.0099 = 0.99%, which is about a factor of 10 too shallow.

I am also sure that the problem is not a flux/DeltaMag conversion problem. I calculate delta_mag = -2.5*log10( f_pct /100 ), where f_pct is the flux in percent. For an in-transit flux of 100% - 10.5% = 89.5% (from the model light curve) I obtain delta_mag ~ 0.12, which is what I find in the attached variable source file ("1.000Msun_1.000Rsun_1.000Mjup_3.000Rjup_5.000d_length20.000d_PLATOSim.txt").

I'm also attaching the input file again.

![image](https://user-images.githubusercontent.com/7735050/47756127-31e90400-dca1-11e8-9411-dc145974b7a9.png)
[1.000Msun_1.000Rsun_1.000Mjup_3.000Rjup_5.000d_length20.000d_PLATOSim.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2532032/1.000Msun_1.000Rsun_1.000Mjup_3.000Rjup_5.000d_length20.000d_PLATOSim.txt)
[inputfile.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2532033/inputfile.txt)

**Comment by JorisDeRidder** [comment]
Hi Rene, just to be sure, your photometric reduction code does first subtract the bias and the sky background, am I correct? If not, and your star is relatively faint, this can affect the transit depth.

**Comment by dk766** [comment]
The photometry is done with the code provided by PlatoSim:
`phot.photometry(inputHdf5File, temp_phot_file, sigmaPSF)`
`time, flux = phot.getPhotometryTimeSeries(temp_phot_file, starId)`
so you are correct there is no bias or background substraction. 
On the other hand though the star in Rene's simulation is pretty bright (mag =  8) so background and bias should not have a large effect.

**Comment by reneheller** [comment]
Is there a way to adjust phot.photometry() to do the bias & background subtraction so that the user can extract a realistic light curve without much ado? I'd like to use PLATOSim for a transit injection-retrieval experiment, but at this point I don't understand why the transit that I'm passing on to PLATOSim does not look like it should after extraction. Thanks for your help!

**Comment by JorisDeRidder** [comment]
If you are using the platophot.photometry() function then the subtraction of the bias and the sky background is actually taken into account (using the true rather than the estimated values in fact).  photometry() might still be the culprit for another reason, though. We'll have to check this. 

A related question: wouldn't it be more reliable to use the Phaedrus photometric pipeline that implements exactly the photometric reduction that is done on-board? platophot.photometry() has always been a quick-and-dirty solution while awaiting the proper implementation of Phaedrus.

**Comment by reneheller** [comment]
Yes, I agree. Using Phaedrus would be the most plausible way to extract the light curves. Unfortunately, Phaedrus doesn't have the latest algorithms from the ATBDs implemented and it seems to me as if this is still going to take a while. Regardless, it would be very useful if PLATOSim could generate reasonable light curves on its own. Could you please check if there is any issue in the PLATOSim photometry API? This is key to a suite of simulations with realistic stellar activity and transits of Earth-sized planets that we would like to do. Your help is very much appreciated.

**Comment by JorisDeRidder** [comment]
Hi @reneheller, could you please make the HDF5 file available through WeTransfer?

**Comment by reneheller** [comment]
Hi @dk766, I just tried to get the HDF5 file for Joris but the download through your PLATOSim web interface won't start (see attached screenshot). Could you please forward the HDF5 file from the simulation output folder "heller_20181030_190806" to Joris?

![screenshot 2018-11-06 at 21 30 13](https://user-images.githubusercontent.com/7735050/48091906-5ac24980-e20b-11e8-8e15-9f59437afba4.jpg)

**Comment by JorisDeRidder** [comment]
HDF5 file received, thanks. We (thanks, Rik) made a time series of a single pixel, and this looks as shown below. The dips are about 10% depth as expected. So, the shallow transit problem is not caused by PlatoSim, but likely by PlatoPhot. 

We can have a look at PlatoPhot to see how we can improve it, but this might take a while. 

![pixel4-4](https://user-images.githubusercontent.com/5747893/48139647-46cc2580-e2a7-11e8-9d46-6e7a3bca1b55.png)

**Comment by dk766** [comment]
I further investigated this issue: I generated 2 identical simulations with the variable sources turned on and off and  I compared one "affected exposures" - an exposure where the transit happens (16000). I noticed that most of the photons get to pixel 4,4 which as Rik's plot from above also show. 
The problem though is that according to the hdf5 file (same for both cases):
```
 Exposures/Exposure016000/colPix = 5.24168237738615
 Exposures/Exposure016000/rowPix = 4.93738833034857
```
so I would expect to see the most photons in pixel (5,5) instead of (4,4) ...

The PlatoPhot code reads this positions and computes for each pixel some weights which are then used to compute the estimatedFlux. Some of the weights are:
```
weight pixel (5,5) = 0.8827
weight pixel (4,4) = 0.00789
...
```

Considering that the estimated flux is computed as:
```
rowStar = int(rowPix[starNr] + deltaRow)         # deltaRow, deltaCol are the 
colStar = int(colPix[starNr] + deltaCol)             # PSF barycenter offsets

for row in range(rowStar-1, rowStar+2):
    for col in range(colStar-1, colStar+2):
         estimatedFlux += weight * (image[row, col] - skyBackground)
```
the contribution of pixel (5,5) having a high weight (which as seen in the screenshots below has similar values in between the 2 simulation) is much higher than the contribution of the pixel (4,4) which has a very low weight although the difference in photons is much larger here.

This seems to be the main source of the shallow values for transit. 
This suggests some problem in Platosim either in setting the colPix, rowPix or in the image.

See attached the screenshots with the 2 simulations that I run 
![sim_no_varsources](https://user-images.githubusercontent.com/18440862/48427047-3bc23b00-e768-11e8-88f2-8c69fec57589.png)
![sim_with_varsources](https://user-images.githubusercontent.com/18440862/48427048-3c5ad180-e768-11e8-885c-45b07f19febf.png)

**Comment by JorisDeRidder** [comment]
Hi Valerian, thanks for the input. I'm not sure I fully understand, though. Looking at your screenshots, I see most of the signal in pixel (5,5): 36964, and not in (4,4): ~20000. So this is compatible with the fact that PlatoSim places the star in pixel (5.2, 4.9), and with the fact that pixel (5,5) gets the largest weight. So far, everything seems OK. Am I missing something?

That said, the weighted photometry might well be the culprit, for example, by poorly estimating the 'radius' of the PSF. Since Gaussian weighting is no longer advocated by our colleagues from Paris, I would propose that we remove it altogether in PlatoPhot, and replace it by a binary mask. I'll contact Reza to ensure that we use the same masking scheme as onboard.

**Comment by dk766** [comment]
If you look at Rik's graph you see a 10% decrease of flux for pixel 4. 
Since I used basically the same settings I expect to see the same difference in flux between the 2 versions (with and without "transit") which seems to be confirmed by the 2 screenshots for all the pixels affected by the star (pixe 4,4 included) with the exception of pixels (4,5) and (5,5)

The value of the pixel (4,4) in the second screenshot is with around 10% smaller but since this pixel has a weight of 0.007 the contribution of its value is minor in the final estimatedFlux. Same for pixels (4,3) (5,3) (5,4) ...

For the pixel (5,5) though that has a much larger weight (0.88) and so the highest contribution to the final flux the difference between the values in the 2 simulations is 0. This explains why the difference between the  estimatedFlux of the 2 simulations is not around 10% but significantly lower. 

What I would have expected is that every pixel (especially the one with the highest number of photons) to be affected in the same way: having a decrease of about 10% in their value. 
However pixels (4,5) and (5,5) which have the highest values as you also point out have exactly the same values in both simulations although all the pixels around them seem to be affected by the "transit". Can this happen ?

**Comment by JorisDeRidder** [comment]
I was just forwarded document PLATO-LESIA-PDC-DD-008 which contains the relevant information of the onboard flux extraction. This seems to contain all the necessary information. We will implement this version in PlatoPhot.

**Comment by JorisDeRidder** [comment]
@dk766 Difficult to predict what is and what isn't possible with a non-Gaussian PSF that is jittering. Let's first implement the onboard masking. Chances are that the problem will be resolved.

**Comment by dk766** [comment]
Some additional info: for the simulation with varsources I extracted some "pixel lightcurves" just a Rik did above. As you can see in the attached image all pixels with the exception of (4,5) and (5,5) have an expected shape. The 2 exceptions though contain so signal and are constant throughout the entire simulation. 
It looks like these 2 are "dead pixels" which is definitely something we might encounter but I am not sure if this is currently implemented in PlatoSim

![pix_lc](https://user-images.githubusercontent.com/18440862/48477896-0fa7c800-e803-11e8-94a2-22ece21c09e0.png)

**Comment by JorisDeRidder** [comment]
I looked into this, and I think I now have a better understanding. The two pixels you are mentioning are suffering from saturation. Because of the relatively large gain of 20 e-/ADU (a value which we got from Anko Börner), of the Plato sensors (FEE + CCD), a full well of 900K e- translates to 45000 ADU. The reason why the star in your simulation already saturated at a pixel value of 37000 ADU is because of a typo in the FEE gain in the inputfile.yaml. That value should be 0.0278 ADU/microV. We will change this in both develop as well as the master branch asap.

**Comment by dk766** [comment]
Nice catch Joris !!!  I think by fixing this you'll implicitly fix the effects reported in this issue too.

**Comment by JorisDeRidder** [comment]
Yes and no :)  By changing the gain, the ADU level of the central pixels will change from 37000 to 45000, but it doesn't change the fact that the star is saturated (i.e. filled up the well of 900 Ke-). This should not happen for a 10th magnitude star. This means that some of the configuration values (e.g. the throughput) in the inputfile.yaml might not be correct. Some time ago we went through a lot of official requirement and reference docs to extract the correct instrument values for the inputfile.yaml, and we're now recomparing with the very latest documents. Some of the documents seem to contradict each other, so we're trying to understand why. We'll report back as soon as possible.

**Comment by JorisDeRidder** [comment]
Valerian kindly emailed me the starcatalog (cf file below). However, this files shows a V=8 star rather than the V=10 star that was mentioned above. For a V=8 star, it is normal that it saturates with a degradation of the light curve if not properly treated. I redid the simulation with the same inputfile as René, but with a V=10 star, and then I do see the 10% transit (cf figure below). So, as far as I can see, I don't see any problem anymore. Would you agree?

[starcatalog_onestar.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/2649396/starcatalog_onestar.txt)

![fluxvstime_v10_sigmapsf05](https://user-images.githubusercontent.com/5747893/49526620-7d9a5900-f8b0-11e8-83ac-019f88fa0311.png)
