### ISSUE TITLE
Update HDF5 dependency to 1.10.2

### ISSUE THREAD

**Issue by SaraRegibo** [IvS-KULeuven/PlatoSim3#322]
Related to #318.

Required (for now in `develop` only):

* download `tar.gz` file from https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.2/src/ and store it under `/dependencies/Downloads`
* remove old `tgz` file from `/dependencies/Downloads`
* update package name in `install_hdf5.py` to `hdf5-1.10.2` and update line 36 (`tar.gz` file instead of `tgz` file)
* in `CMakeLists.txt`: update line 70 & 110
* update documentation pages (local pages, not the website)
* send email to users (that install PlatoSim via GitHub) to tell them they need to re-install HDF5 (and how they have to do that)

**Comment by SaraRegibo** [comment]
@WimDeMeester I've committed al changes that are required to switch to version 1.10.2 of the HDF5 library, at least when you install PlatoSim from GitHub.  TBD how the scripts from the Jenkins build (for the conda installation procedure) need to be adapted.

**Comment by WimDeMeester** [comment]
Build script works fine. Installation with python 3.7 on Mac and Linux was tested.

**Comment by SaraRegibo** [comment]
Closed by pull request #323.

**Comment by hposborn** [comment]
Can I re-open this and suggest replacing hdf5-1.10.2 with hdf5-1.10.5 ?

The hdf5-1.10.2 doesn't install with gcc-8.1 ("H5detect.c:1363:1" throws an error due to, I think, a single line which is no longer compatible, see https://forum.hdfgroup.org/t/1-10-2-h5detect-compile-error-gcc-8-1-0-on-centos-7-2-solved/4441). I spent ages figuring this out. Installing hdf5-1.10.5 and replacing all lines with 1.10.2 to 1.10.5 fixed the problem.

**Comment by JorisDeRidder** [comment]
Thanks Hugh for signaling this. We'll take this up asap. I'll create a different issue, though.
