### ISSUE TITLE
Check SmearingMap values

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#386]
I am a little confused about the SmearingMap values.

When I run a simulation I get SmearingMap values which level are quite similar to the imagettes values. Therefore, when I subtract smearing* to imagette to do the photometry I get negative values.  I have a doubt about how the background is taken into account within the smearing values. I may be wrong but may you check this computation, particularly theses line of code:

`Detector.cpp 1867: arma::Row<float> openShutterSmearingOutsideSubField = arma::conv_to<arma::Row<float>>::from(numExposedNonSubFieldRowShifts) * camera.getTotalSkyBackground();`

`Camera.cpp 666: totalSkyBackground = floor(userGivenSkyBackground * exposureTime * transmissionEfficiency);`

I am not very familiar with Platosim code but is it seems that getTotalSkyBackground function returns photons/pix/exposure, that means by 21s second ?

*Prior to subtract smearing I have subtracted offset to smearing.

_PlatoSim version 3.3.6-2-gb084a69_

**Comment by SaraRegibo** [comment]
The total sky background is indeed what is accumulated during the exposure of the CCD (i.e. it's already multiplied with 21s).  This is what happens on line 666 in `Camera.cpp`.

What happens in the `applyOpenShutterSmearing` is the following:
* The time over which open-shutter smearing is "active" is  - in absence of mechanical vignetting - the time it takes to do the readout before the next integration starts.  For normal cameras this is the entire readout time (i.e. for the image area + parallel over-scan)  For the fast cameras, this is the time for the frame transfer (i.e. to move the charges from the image area to the storage area) + parallel over-scan.
* When mechanical vignetting is taken into account, part of a column may be shielded off (i.e. falls outside the FOV).  This results in a shorter time over which open-shutter smearing is accumulated.  More specifically, it is the time to read out the pixels in that columns that are actually in the image area and in the FOV +  the parallel over-scan. -> line 1936: `openShutterSmearingTime` is calculated per column and denotes the time over which open-shutter smearing is accumulated
* What is the average flux in a pixel in a given column, as accumulated during the readout (due to the absence of a shutter)?  The contribution for of pixel in the sub-field (within the FOV): the true flux in the pixel map, but scaled with the open-shutter smearing duration instead of with the exposure time.  The contribution for a pixel inside the FOV but outside the FOV: the total sky background, but scaled with the open-shutter smearing duration instead of with the exposure time.  Idem for pixels in the parallel over-scan.  Now take the average over all these contributions (per column, and - as stated - scaled with the open-shutter smearing duration instead of with the exposure time). -> line 1905 for the contribution in the sub-field; line 1909 for the contributions in the FOV but outside the sub-field + the parallel over-scan; line 1939 for the scaling and dividing by the number of summed contributions (per column).
* Note that the total sky background (as calculated in `Camera`) does not yet take into account the natural vignetting, polarisation, particulate + molecular contamination, and QE. -> lines 1914 - 1930

**Comment by SaraRegibo** [comment]
Note that the pixel map (i.e. the sub-field itself) and the smearing map (i.e. the parallel over-scan) receive the same contribution from the open-shutter smearing, as can be seen on lines 1945 - 1951 in `Detector`.  This is expected behaviour.

@manugr788 Could you assess whether the flux in the pixel map is as expected for the given sky background?

**Comment by manugr788** [comment]
Thank you Sara for your very comprehensive reply .
Actually I don't understand the value of the flux in the pixel map because, except for the flux coming from the stars, the background flux seems to be the same within smearing map and pixel map while the former is accumulated during 4s whereas the latter is accumulated during 21s.

Run the following very basic simulation :
[https://upload.obspm.fr/get?k=yzQrFQ4PEIAakXsTkDa](https://upload.obspm.fr/get?k=yzQrFQ4PEIAakXsTkDa)

The background, without offset, is around 43 ADU for both pixel and smearing maps.
 
_PlatoSim version 3.3.6-2-gb084a69_

**Comment by manugr788** [comment]
See attached files:
[simu_platosim](https://user-images.githubusercontent.com/12544881/65712113-9ae62100-e096-11e9-80b8-7b54da54d83a.PNG)
[platosim_basic_test_lesia.tar.gz](https://github.com/IvS-KULeuven/PlatoSim3/files/3659164/platosim_basic_test_lesia.tar.gz)

**Comment by SaraRegibo** [comment]
Well, actually, the background flux in the pixel map is supposed to be accumulated over the whole image cycle (i.e. exposure + readout), so over 25s instead of 21s...

I'll have a look at your simulation and get back to you.

**Comment by SaraRegibo** [comment]
I tried to reproduce your simulations with the latest version of the `develop` branch.  In this version, we have kicked out the exposure time and introduced the image cycle time as a new configuration parameter.  This was discussed in #369.  As a result - given your other configuration parameters - the exposure time will be 17.538964s (as opposed to the 21s you used as input).  This is not crucial in your simulations, but it's good to know this to understand the calculations below.

Ok, so I switched off *all* CCD effects (so also the open-shutter smearing) and set the pointing to (0°, 0°) to make sure there is no source in the imagette.  In that case, you expect the flux accumulated during the whole image cycle is:

```
exposureTime = sim["ObservingParameters/CycleTime"] - sim.getReadoutTime()[0]     # 17.538964s
estSkyBackground = sim["Sky/SkyBackground"] * sim["Telescope/TransmissionEfficiency/BOL"] * exposureTime     # 342 * 0.8162 * 17.538964
```
This gives you the expected flux value to find back in the pixel map (since all effects have been switched off, meaning noise effects as well as multiplication with the gain): 4895.8, which is exactly what I see in the pixel map (only there the values have been rounded down to 4895).  Since all effects are switched off (incl. open-shutter smearing), we expect the smearing map to contain only zeroes, which is indeed the case.

Now switch on *only open-shutter smearing*.  In that case, to estimate the sky background that is accumulated (in the pixel map) over the whole image cycle, you use the cycle time instead of the exposure time in the formula above (so `342 * 0.8162 * 25`). This yields a value of 6978.51 as an estimate, and we find back 6991 in the pixel map (which is close enough).  The smearing map should then contain the difference between the two, as this is what is accumulated during the readout due to the absence of a shutter:

```
estSmearing =  sim["Sky/SkyBackground"] * sim["Telescope/TransmissionEfficiency/BOL"] * exposureTime -  sim["Sky/SkyBackground"] * sim["Telescope/TransmissionEfficiency/BOL"] * sim["ObservingParameters/CycleTime"]
```

This value, 2082.67, is very close to what we actually find the in the smearing map (2096).

**Comment by SaraRegibo** [comment]
The problem arises when you switch on mechanical vignetting, because the sub-field falls outside the FOV.  During the exposure, that part of the image area of the CCD is "shielded off".  During readout, the rows are shifted down, but they only start accumulating flux as soon as they enter the FOV.  The rows in the pixel map and the rows in the parallel over-scan map (i.e. the smearing map) spend the same time in this region, so it is expected behaviour that the the pixel and the smearing map see the same background contribution in this particular case.

[test.py.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/3662187/test.py.zip)

**Comment by manugr788** [comment]
Oh, I understand everything now ! Thank you very much Sara for your reply. I forgot the effect of mechanical vignetting since this effect is not implemented within PIS and I was trying to reproduce PIS simulation with Platosim.
I'm very sorry for wasting so much of your time !

**Comment by SaraRegibo** [comment]
Glad it's sorted out! :) You can close the issue.

**Comment by manugr788** [comment]
I ran a last test, everything is perfect.
