### ISSUE TITLE
 NumBiasPrescan

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#397]
I don't understand the default value of  NumBiasPrescanRows/Columns in the inputfiles/inputfile.yaml
```
    NumBiasPrescanRows:              30              # Nr of rows of the prescan strip to determine the bias [pixels]
    NumBiasPrescanColumns:           30              # Nr of columns of the prescan strip to determine the bias [pixels]
```
If these values define the prescan strip to determine the bias then I agree with, but actually these values are also used within Platosim code to compute the readout time before next exposure, so they must reflect the true readout process of the serial prescan area therefore the values should be something like:
 ```
    NumBiasPrescanRows:              4510              # Nr of rows of the prescan strip to determine the bias [pixels]
    NumBiasPrescanColumns:          25              # Nr of columns of the prescan strip to determine the bias [pixels]
```
or maybe:
 ```
    NumBiasPrescanRows:              4510+30              # Nr of rows of the prescan strip to determine the bias [pixels]
```
I am not sure that NumBiasPrescanRows and NumBiasPrescanColumns should be used to compute the readout time. I think they should only be used to size the biaisMap to dump into the HDF5 since it's true that only some serial prescan pixels are used to compute the bias. But anyway, 4540*25 pixels are read by the register for the serial prescan even if some of those pixels will be discarded after reading.

**Comment by drsamadi** [comment]
In order to be compliant with PLATO-MSSL-PL-TN-008,i1.0

[02_PLATO-MSSL-PL-TN-008_01_B_PLATO_CCD Definition.docx](https://github.com/IvS-KULeuven/PlatoSim3/files/3690691/02_PLATO-MSSL-PL-TN-008_01_B_PLATO_CCD.Definition.docx)

I think we shall rather introduce the following terminology
   NumSerialPrescanPixels:          25
   NumSerialOverscanPixels:          25
   NumParallelPrescanPixels:          0
  NumParallelOversanPixels:          30

see figure 4.1 (right) in the above mentioned document.

These values constraint the cumulated transfer time.

**Comment by SaraRegibo** [comment]
In reality, you would have two bias maps of 30 x 4510 pixels (because each readout register has 30 elements more than half the CCD size and the two detector halves are read out simultaneously).  The total readout time (for normal cameras) is calculated based on:

- parallel transfer of all the rows of the CCD itself (i.e. 4510) + the rows of the parallel over-scan
- for each of these parallel transfers, there's a serial readout of half the CCD width (2255) + the extra 30 pixels from the bias map (i.e. serial pre-scan)

However, for performance issues, we want to avoid - in case of full-frame simulations - we want to avoid having to store two bias maps of 30 x 4510 pixels.  So the `NumBiasPrescanRows ` is only there to decide how big the bias maps should be but not to compute the readout time.

**Comment by SaraRegibo** [comment]
```
readoutTimeBeforeNextExposure = numRowsDump * parallelTransferTimeFast + numRowsReadout * (numColumnsReadout * serialTransferTime + parallelTransferTime)
```

with 
- `numRowsDumped` the number of rows that are dumped in the readout register without being read out serially (which is zero in case of the normal cameras in nominal readout mode)
- `numRowsReadout` = 4510 + `numRowsSmearingMap`
- `numColumnsReadout = numColumns / 2 + numColumnsBiasMap` (because you read out the two CCD halves simultaneously and you have `numColumnsBiasMap` additional pixels in each readout register)
- `parallelTransferTimeFast` is the time it takes to move a row to the readout register in case it will not be read out by the readout register (which is not applicable in case of the normal cameras in nominal readout mode)
- `parallelTransferTime` is the time it takes to move a row to the readout register in case it will be read out by the readout register
- `serialTransferTime` is the time to read out one pixel from the readout register

**Comment by SaraRegibo** [comment]
@manugr788 I think the readout time is calculated correctly in PlatoSim.  It is done as explained in the comment above.  We do need to take into account the number of columns in the serial pre-scan (i.e. the bias map), as this means the (serial) readout of an additional 30 pixels in the readout register.  Such a readout only takes 340ns, but still... :)

@drsamadi I would propose you to open a separate issue if you would want us to change the names of these configuration parameters, to be consistent with the MSSL nomenclature.  But I agree consistency would be a good thing!

**Comment by manugr788** [comment]
@SaraRegibo Ok, I agree with you, It's now clear for me. Thank you for your complete reply. I closed the issue.
