### ISSUE TITLE
Save input IDs and CCD position in HTF5 file

### ISSUE THREAD

**Issue by hposborn** [IvS-KULeuven/PlatoSim3#400]
The IDs used in the "starcat.txt" (eg star positions) and then the "varcat.txt" (eg the file locations of intrinsic variability of the stars) are seemingly lost in the resulting HTF5 file. Instead there are new IDs which are integer values and have to be correlated with the input catalogue using the RA/Dec values. It's not impossible, but more effort than is necessary.

Similarly, the StarCatalogue saved in the HTF5 file has two arrays: 'colPix' and 'rowPix'. These would be useful to check if stars are fully in the SubField... **IF** A) the position of those arrays were relative to the subField (They are currently relative to the CCD) or B) the CCD pixel position of the subField was saved (I would have thought `InputParameters/SubField` or `InputParameters/CCDPositions` might have this info, but both are empty). this step would also not be important if platophot.photometry did a similar "check" for whether a target was fully on the subField or not - currently it throws an error at `throughputMap[int(rowTarget[k]), int(colTarget[k])]` if the x/y is 

Thanks,

Hugh

**Comment by SaraRegibo** [comment]
Regarding the 2nd part of your description:

Information on the position of the sub-field on the CCD is saved (**as attributes**) in the HDF5 file:

- `InputParameters/Subfield/ZeroPointRow`
- `InputParameters/Subfield/ZeroPointColumn`

If you use a GUI (e.g. `HDFCompass`) to check the values of attributes in a group of an HDF5 file, you must make sure you open that group as attributes (instead of as group).  Otherwise you will indeed see an empty `Subfield` group (because there are no datasets present in this group, only attributes).  Have a look at the attached image and it will become clear what I mean!

Based on this information it is straightforward to convert between coordinates on the CCD and coordinates in the subfield:

- `rowCCD = rowSubField + zeroPointRow`
- `columnCCD = columnSubField + zeroPointColumn`

---

<img width="943" alt="Screenshot 2019-10-15 at 11 46 13" src="https://user-images.githubusercontent.com/10076088/66820663-6e108580-ef41-11e9-91b9-d2cf8779cce8.png">

**Comment by SaraRegibo** [comment]
@JorisDeRidder Could you comment on the 1st part of Hugh's description, please?

**Comment by hposborn** [comment]
> Information on the position of the sub-field on the CCD is saved (as attributes) in the HDF5 file:

Ooh ok. I was being an idiot then and looking in `Group._v_children` and assuming attributes would also appear there. I see them now! Thanks!
