### ISSUE TITLE
The peculiar case of *not* convolving with the analytic non-Gaussian PSF

### ISSUE THREAD

**Issue by SaraRegibo** [IvS-KULeuven/PlatoSim3#402]
This issue was notice when testing the CTI for the verification & validation plan.

I tried simulating a single column, with all effects switched off.  It is important to note that also **convolution with the PSF is switched** off during the whole process described below!  I did the configuration with the following script:

````
from simfile import SimFile
from simulation import Simulation
from validation import switchOffAllEffects
import os
import math
import numpy as np

sim = Simulation("CTI")
switchOffAllEffects(sim)
sim.outputDir = os.environ["PLATO_WORKDIR"]

# One full-column exposure

sim["ObservingParameters/NumExposures"] = 1
sim["SubField/NumRows"] = 4510
sim["SubField/NumColumns"] = 1

# Make sure no sources are located in the sub-field

sim["ObservingParameters/DecPointing"] = -sim["ObservingParameters/DecPointing"]
````
At this point, the only flux that is received comes from the sky background (works fine).

I then performed a couple of simulations with a single 12.5-magnitude star within the column.  For the different simulations the source is be located further and further away from the readout register (at row 0, 500, 1000,...):

````
starCatalogFilename = os.environ["PLATO_WORKDIR"] + "generatedFromPixelCoordinates.starcat"
sim["ObservingParameters/StarCatalogFile"] = starCatalogFilename

sim["Sky/SkyBackground"] = 0

positionRows = np.arange(0, 5000, 500)

columns = []

for row in positionRows:
    print(row)
    
    sim.createStarCatalogFileFromPixelCoordinates(np.array([row + 0.5]), np.array([0.5]), np.array([12.5]), np.array([1]), starCatalogFilename)
    output = sim.run(removeOutputFile = True)
    column = output.getImage(0)
    print(np.min(column), np.max(column))
    
    columns.append(column)
````

Since all effects (also the CTI) are switched off, you expect the minimum value in the output simulations to always be the same, and the same holds for the maximum value.  This is indeed the case the PSF model is either a Gaussian PSF or a pre-computed PSF.  However, when setting `sim["PSF/Model"] = "AnalyticNonGaussian"` this is no longer the case , even though I do not convolve with the PSF (I checked the log file and the configuration file to be sure I didn't accidentally mess this up, but no).

These are the printouts:

````
0     # row where the source is located


0.0 70703.9     # min & max value in the simulated column
500


0.0 74462.016
1000


0.0 78561.59
1500


0.0 80057.63
2000


0.0 76639.58
2500


-1.4658031e-19 71563.97
3000


-3.7192526e-15 65975.33
3500


0.0 63782.75
4000


0.0 73770.055
4500


0.0 69823.234
````

**Comment by carstenpaproth** [comment]
When you use the analytic non-Gaussian PSF then the PSF shape changes with the position in the FOV. Furthermore the integral of the analytic PSF is applied to neighboring pixels instead of a convolution. So the signal of a star gets spread over several pixels depending on the shape of the analytic PSF, that is why you cannot expect a constant min and max value in your setup.

**Comment by SaraRegibo** [comment]
Hi @carstenpaproth, thanks for your input!  I agree with your analysis, provided the `IncludeConvolution` is set to `yes`.  When set to `no`, I would assume the PSF is not applied, also in case the application of the PSF is not a convolution but an analytical function that is applied.

**Comment by JorisDeRidder** [comment]
@SaraRegibo I believe the following sentence in your analysis is wrong: "Since all effects are switched off, you expect the minimum value in the output simulations to always be the same, and the same holds for the maximum value".

As Carsten mentioned, the shape of the PSF (including its maximum value) changes when you change the position of the star on the CCD.

**Comment by SaraRegibo** [comment]
@JorisDeRidder By "switching off all effects" I also mean:

````
sim["CCD/IncludeConvolution"] = "no"
````

I had assumed that this also would mean that the analytical non-Gaussian PSF is not applied.   In that case I think my sentence was correct...

Maybe it was incorrect of me to make that assumption, but the least we can conclude is that it is confusing...

**Comment by JorisDeRidder** [comment]
The analytical non-Gaussian PSF does not involve convolution, it involves summing. Hence the IncludeConvolution switch does not apply to it. Only a mapped PSF involves convolution. Possibly the confuses arises because all the "Include\Effect" switches are bundled together in the section 'CCD' rather than putting them close to their relevant parameter. This can sometimes make it unclear to which parameter a switch applies.

**Comment by SaraRegibo** [comment]
Ok, so my assumption was incorrect.  I'll update the documentation to make thing more clear!
