### ISSUE TITLE
Cosmics model representativity

### ISSUE THREAD

**Issue by denisGrBach** [IvS-KULeuven/PlatoSim3#409]
I started to look into the influence of cosmics w.r.t. the FGS performance. The currently implemented model seems to be pretty simplified. Is there any experience with its representativity? At least with the default options I already see a non negligible increase for the FGS noise. 
Some time ago I send around a paper describing a more fancy approach (see attachement). What do you think? 
[stardust.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/3972899/stardust.pdf)

**Comment by JorisDeRidder** [comment]
There are several aspects concerning the representativeness of the cosmics model in PlatoSim. The first is the cosmic hit rate, defaulted to 10 hits/cm^2/s, which we took from Req. 790 in the Anko data package v1.7.  The intensity is currently uniformly distributed, while in reality there are more low-energy hits. The trail length is also uniformly distributed, while in reality there are more short-trailed hits. Intensity and trail length could be relatively easily improved by implementing skewed distributions. Then there is the shape of the cosmic trail, which we currently model as a 1D trail with an exponential decay.  In reality there can be diffusion of electrons in the substrate transversal to the trail as well. 

We looked at the paper of Rolland et al. but we didn't see it as a feasible option. First, an advanced code like STARDUST is not trivial to duplicate. Secondly, we were also concerned about the performance hit that PlatoSim would suffer since the electron diffusion (i.e. the trajectory segments crossing the substrate) is calculated using a Monte Carlo technique.
