### ISSUE TITLE
Jitter smoothing hidden in Charge diffusion

### ISSUE THREAD

**Issue by s-geiser** [IvS-KULeuven/PlatoSim3#430]
Discussion revealed that jitter smoothing is effectively always applied by using charge diffusion (PSF from file). This is unclear from the input file.

Also is there a way to control the amplitude of the jitter smoothing?

**Comment by carstenpaproth** [comment]
For clarification, in simulations with convolution with sampled PSFs the movement of stars on the CCD is restricted by whole subpixel steps which causes quantization artifacts in the FGS simulation. To avoid these artifacts, it would be necessary to use large number of subpixels per pixel or resample the PSF for every star and every movement so that sub-subpixel movements are considered.
With the help of the analytical PSF we can have a small number of subpixels per pixel and sub-subpixel movements. For every star a small analytical Gaussian PSF (sigma = 0.5 subpixels), which can be shifted with sub-subpixel accuracy, is applied to the subpixels before the convolution with the sampled PSF. This results in a sub-subpixel movement and resampling of the PSF for every star and we call it jitter smoothing. 
The disadvantage of this procedure is that it blurs the PSF by the subpixel Gaussian, but the blurring can be used to simulate the charge diffusion by simply increasing the sigma of the Gaussian accordingly. So we kill two birds with one stone.

Actually, it would be more efficient, in the case of a large number of subpixels per pixel, to simulate charge diffusion by the convolution of the sampled PSF with the charge diffusion Gaussian and use that convolved sampled PSF with the small subpixel Gaussian (sigma = 0.5 subpixels) for the jitter smoothing.

To answer the question, the amplitude of the jitter smoothing depends on the size of the subpixels.

**Comment by SaraRegibo** [comment]
The suggestion to improve the efficiency will not work unfortunately...

When a given star falls on the sub-field, we calculate its sub-pixel coordinates, round those and then put the source at that (rounded) sub-pixel location.  Only afterwards to we apply the convolution.

If we decide to include jitter smoothing (or charge diffusion, for that matter), we calculate the star's sub-pixel coordinates and we calculate how the flux gets spread out (by the jitter smoothing / charge diffusion) based on these **non-rounded** sub-pixel coordinates.  The smeared out flux is inserted into the image and only afterwards the PSF is applied.

If we would squeeze the jitter smoothing / charge diffusion into the (convolution with the) PSF, we would end up using the **rounded** sub-pixel coordinates to calculate the smearing of the flux (by the jitter smoothing / charge diffusion).  Then you would re-introduce the "jumps"...

**Comment by carstenpaproth** [comment]
@SaraRegibo 

Exactly, that's why we would still need the jitter smoothing to avoid the jumps. The more efficient solution would be to convolve the optical PSF with a large charge diffusion kernel and use that as the overall PSF, then use the small jitter smoothing to distribute the flux without jumps. Currently, the charge diffusion is handled by the jitter smoothing, which is OK for a small number of subpixels per pixel. But for a larger number of subpixels per pixel, that could be too slow.

**Comment by SaraRegibo** [comment]
Since applying charge diffusion uses the **non-rounded** sub-pixel coordinates, it indeed acts as a sort of jitter smoothing, too, though - typically - on a larger scale.

Though this may not be clear at first from the configuration file (not sure how we could improve upon this), it is clear from the documentation, I believe (see the screenshot below).

---
![Screenshot 2020-03-02 at 11 02 08](https://user-images.githubusercontent.com/10076088/75665988-5417db00-5c75-11ea-8065-287c70072d6c.png)

**Comment by SaraRegibo** [comment]
@carstenpaproth Ok, that's a fair point! :)  I'll have a look at the code to see whether this can be solved without (too many) drastic changes.

As for the analytic non-gaussian PSF: does a convolution of that PSF with a gaussian kernel correspond to simply increasing parameter `Sigma`?

**Comment by carstenpaproth** [comment]
@SaraRegibo 
No, increasing sigma increases the size of the analytic non-Gaussian PSF. Only in the case of a convolution of 2 Gaussian PSFs increasing sigma to sqrt(sigma1^2 + sigma2^2) would be sufficient. The convolution of the analytic non-Gaussian PSF with a Gaussian kernel is accomplished with the ChargeDiffusion parameters.

**Comment by SaraRegibo** [comment]
@carstenpaproth Do you mean the parameters in  `psfallv3.txt`?

How should we adapt these parameters (because we would still want to apply an analytical function, which combines the analytical PSF and the charge diffusion)?

**Comment by carstenpaproth** [comment]
@SaraRegibo 
I mean the ChargeDiffusionStrength and IncludeChargeDiffusion parameters in the yaml file. The charge diffusion (convolution with a Gausssian kernel) is already implemented in the analytical non-Gaussian model, you don't need to adapt anything for it.
