### ISSUE TITLE
question: jitter and intra-exposure displacements

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#455]
Hi , 
I'm generating a simulation with a jitter imposed form a file and sampled at 8Hz.
I would like to know the star displacement during each exposure. 
I generally derive the star positions from the the data set "StarPositions". However, this one is sampled at the cadence of the exposure (25s).
How to get the star displacements within the imagettes  at the cadence of 8Hz? 
Here attached my YAML file.
Réza

[psffit115.yaml.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/4502408/psffit115.yaml.txt)

**Comment by SaraRegibo** [comment]
You can find the jitter angles in the output HDF5 file in the group `ACS`.  The datasets in these groups are the following:

* `Time` [s]
* `Yaw` [arcsec]
* `Pitch` [arcsec]
* `Roll` [arcsec]

In the same group, you can find the right ascension and declination (both in degrees) of the platform pointing in the groups `PlatformRA` and `PlatformDec`.  You can use these to work out the displacement at the cadence from the jitter file (rather than at the cadence of the image cycle), from the `Time` dataset.

Note that you can use the convenience functions in `h5` (found the the `python` directory) to access the content of these datasets.

**Comment by drsamadi** [comment]
Hi Sara,
I've already looked at those data but they are provided at the exposure cadence. In my simulation with 990 exposures I have 990 values of yaw, pitch, and roll.
Furthermore, I want the star displacement in the CCD frame. How to translate the ACS data into CCD displacements ?
thanks
Réza

**Comment by JorisDeRidder** [comment]
Hi Réza, I understand what you want, but I'm afraid that's a feature that's not within PlatoSim's current capabilities. Is this something that you can work around, or is this a must-have feature that needs to get high priority?

**Comment by drsamadi** [comment]
Hi Joris
the jitter/drift correction algorithm needs the information about  the displacement of any target in the CCD frame (P5 sample only). 
This information will derived by the on-ground data processing pipeline by combining the ACS information coming from the Fast Camera (and perhaps also the ACS data from the plateform, TBC). 
Then we will have to translate the de-pointing information (ACS)  in terms of CCD displacements. 
To do this, we will combine the ACS data with the inferred N camera attitude and the Image Geometry Model. The underlying algorithms will be studied by our Brazilian colleague Fabio Fialho (WP 3235 100) in collaboration with Elena Duarte (WP 324 star centroids). 
Then in principle we will derive the star displacements by our self. However, to check our calculations  as well as to be able  right now to operate our  jitter/drift correction algorithm with PLATOSim simulations we need the information about the star displacements. To derive this, it would be enough if you can  provide us the algorithm (e.g. in python or C)  your are using to infer the change in the star focal position induced by the plateform jitter.  There is no need to implement a new feature into PLATOsim. 
Réza

**Comment by SaraRegibo** [comment]
Hi @drsamadi,

we cannot offer you an off-the-shelf answer to your question, I am afraid, but maybe the following suggestions will already help you:

* Have a look at the `updatePlatformPointingOrientation` method in the `Platform` class. This method calculates the new (sky coordinates of the) platform pointing, for a given time (using the jitter angles at that moment).
* For a source of interest, apply this method to the sky coordinates of this source from the star catalogue (instead of on the platform pointing), using the timepoints (and the jitter angles, of course) from the jitter file.
* Assume the source falls on a given pixel _(row, column)_ at time _t=0_ .  At that moment, this particular pixel will "see" the sky coordinates of this source from the star catalogue.  Once you start "jittering" (i.e. _t > 0_),  this particular pixel will no longer "see" the same sky coordinates, since the source will move over the CCD due to the jitter.
* The outcome of this exercise if a time series of sky coordinates this particular pixel will "see" as we are "jittering".
* The source will of course stay at the same position in the sky and only the platform pointing will change (making the source move over the CCD), but the effect (of the source moving over the CCD) would be the same if the platform pointing would be stable and the source would be moving over the sky (to the sky coordinates you have calculated now).
* Now convert these sky coordinates to focal-plane coordinates with the method `skyToFocalPlaneCoordinates` in `referenceFrames.py`, using the **original** platform pointing (i.e. the platform sky coordinates for time _t=0_, as listed in the configuration file). So you end up with a time series of focal-plane coordinates (in mm).  You can use these to calculate the displacement of the source on the CCD in mm.
* If you want everything in pixels instead of in mm, use the method `skyToPixelCoordinates` (also from `referenceFrames.py`) instead.

**Comment by SaraRegibo** [comment]
It occurred to me that  this

> but the effect (of the source moving over the CCD) would be the same if the platform pointing would be stable and the source would be moving over the sky (to the sky coordinates you have calculated now).

is actually not true.  The star will move in the opposite direction. If the real jitter will move the source over _(Δrow, Δcolumn)_ over the CCD, then the approach I proposed, will move the star over _(-Δrow, -Δcolumn)_.  So the displacement of the source will be equally big but in the opposite direction.

**Comment by drsamadi** [comment]
Hi Sara,
questions:
1) the data stored in  ACS are sampled at the exposure cadence while my jitter file provides the 3 angles at the cadence of 8Hz.  Then are the ACS angles given in output averaged over 25s, or  over the integration time (~21s)  , or or just given (sampled) every 25s ? 
2)  Is the star jitter displacement at 8Hz taken into account during the integration when forming the image ? 
thanks for your help
Réza

**Comment by SaraRegibo** [comment]
Hi Réza, I am going to pass on your questions to Joris, as he is more familiar with the intricacies of the jitter!

**Comment by drsamadi** [comment]
Sara,
concerning your explanation below, it is strange to apply the jitter rotation matrix on the star positions in the inertial frame. Usually the three angles (yaw, pitch and roll) reflect  the change of the star coordinates in the spacecraft reference frame (which for PLATOSim  I assume  is identical to the boresight frame of the F cam).
 
Assuming a N-Cam aligned with the F-came,, I implemented the transformation by applying the jitter rotation matrix on star positions given in the boresight frame of the camera. Then I translate the new star boresight frame position into focal plane position using a gnomonic projection and the distortion model.  I 'm able to retrieve exactly the star displacements recorded in the "StarPositions" data set. Here below the code, can you have a look ? Of course it will not work in the (real) situation when the  N cam is not aligned with the F-cam (in that case I will have to apply a second rotation matrix to go from the Fcam boresight frame to the N-cam boresight frame). 

[StarJitter.py.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/4529149/StarJitter.py.txt)

I tested my calculations first with a linear drift, sampled at 8Hz and specified  by JitterFileName . I get exactly the same displacements than those given in the "StarPostions" data set (but here a the cadence of 25s). 
 Then I applied my jitter/drift correction, the latter successfully  correct the impact of the drift as shown below:

![Figure_1](https://user-images.githubusercontent.com/19569211/80219469-cc31ca00-8642-11ea-9f77-18d263cd7a75.png)

However when I applied my drift/jitter algorithm on a platosim simulation based on a OHB jitter time-serie sampled at 8Hz (and artificiality amplified by a factor 7), the correction is not satisfactory as this is shown in the two following figures:

![Figure_2](https://user-images.githubusercontent.com/19569211/80223571-bfb07000-8648-11ea-8fb5-8c4ac9819fa8.png)

![Figure_3](https://user-images.githubusercontent.com/19569211/80223589-c4752400-8648-11ea-8d8d-f9c95778260a.png)

Given the fact that  my star displacement calculations gives results consistent with the star displacement recorded in the "StarPositions" data set (sampled at 25s) and given the fact my algorithm successfully correct the impact of the linear drift,  I don't think that the problem comes neither for my transformation nor from my jitter/drift correction algorithm (which has been extensively been tested with PIS) . This is illustrated below with a PIS simulations based on the same jitter file (amplified by a factor 7 as well). 
Therefore I'm puzzle with the results obtained with the jitter time-series and I wonder if the star displacements is properly taken into account during the integration time. Or may be I did something wrong. 
 
![Figure_4](https://user-images.githubusercontent.com/19569211/80223376-80821f00-8648-11ea-96d7-5ebeb237fe72.png)

![Figure_5](https://user-images.githubusercontent.com/19569211/80223395-8546d300-8648-11ea-9220-6fb7759a0d18.png)








> Hi @drsamadi,
> 
> we cannot offer you an off-the-shelf answer to your question, I am afraid, but maybe the following suggestions will already help you:
> 
>     * Have a look at the `updatePlatformPointingOrientation` method in the `Platform` class. This method calculates the new (sky coordinates of the) platform pointing, for a given time (using the jitter angles at that moment).
> 
>     * For a source of interest, apply this method to the sky coordinates of this source from the star catalogue (instead of on the platform pointing), using the timepoints (and the jitter angles, of course) from the jitter file.
> 
>     * Assume the source falls on a given pixel _(row, column)_ at time _t=0_ .  At that moment, this particular pixel will "see" the sky coordinates of this source from the star catalogue.  Once you start "jittering" (i.e. _t > 0_),  this particular pixel will no longer "see" the same sky coordinates, since the source will move over the CCD due to the jitter.
> 
>     * The outcome of this exercise if a time series of sky coordinates this particular pixel will "see" as we are "jittering".
> 
>     * The source will of course stay at the same position in the sky and only the platform pointing will change (making the source move over the CCD), but the effect (of the source moving over the CCD) would be the same if the platform pointing would be stable and the source would be moving over the sky (to the sky coordinates you have calculated now).
> 
>     * Now convert these sky coordinates to focal-plane coordinates with the method `skyToFocalPlaneCoordinates` in `referenceFrames.py`, using the **original** platform pointing (i.e. the platform sky coordinates for time _t=0_, as listed in the configuration file). So you end up with a time series of focal-plane coordinates (in mm).  You can use these to calculate the displacement of the source on the CCD in mm.
>

**Comment by SaraRegibo** [comment]
Hi Réza,

Thanks for the feedback.  I think it would have been wiser to apply the `updatePlatformPointingOrientation` method to the platform pointing (yielding a time series of platform pointings, as the platform changes due to the jitter), and then convert the sky coordinates of the source (from the star catalogue) to FP or CCD coordinates for the time series of the platform pointings (and work out the displacement on the CCD from there).  The method I proposed before boils down to the same thing, but this one is more correct (and intuitive).  Apologies for the confusion!

Would you mind sending me the file you have used for the linear drift, please?

**Comment by drsamadi** [comment]
Hi Sara,
you can download this package:  
https://upload.obspm.fr/get?k=JRXjYimIvbRBKgHt7ve
which contains my simulation together with the jitter file used as input.
I discover an error in my side, for a strange reason the OHB jitter file started at time=1000s,  while PLATSOm starts at t=0 and generated the first 1000 s assuming a zero jittter, in my derivation of the star displacement I assumed that the jitter file started at t=0s.  This induces a time-shift between the real displacement and the inferred one. 
I run again my jitter correction, this improves the correction but still the corrected light-curve  is far to be satisfactory as shown below. This is strange because the platosim light-curve (black) looks to be more noisy than the modelled one (blue).  Could this  be a numerical issue ?

![Figure_1](https://user-images.githubusercontent.com/19569211/80418992-8d1ca680-88d8-11ea-9ddb-3313cbe2794d.png)

![Figure_2](https://user-images.githubusercontent.com/19569211/80419000-90b02d80-88d8-11ea-9e28-2a82c8023673.png)

**Comment by drsamadi** [comment]
Hi 
I run a similar PLATOSim simulations, however this time using MappedFromFile PSF (instead of AnalyticNonGaussian) and with the convolution activated. Of course, every thing is identical (except the PSF). 
I then run the jitter/drift correction algorithm on it and get much better results as shown below. The correction is not fully perfect but there is a clear correlation between the raw LC and the modelled one. Some peaks are not perfectly corrected  I don't know why. 
In any case the results here are more satisfactory than when AnalyticNonGaussian PSF is used.

![Figure_1](https://user-images.githubusercontent.com/19569211/81177606-39c8e900-8fa7-11ea-8fda-e95470fe3753.png)

![Figure_2](https://user-images.githubusercontent.com/19569211/81177622-3f263380-8fa7-11ea-80d2-9f256fe874f9.png)

**Comment by carstenpaproth** [comment]
I tried to reproduce the weird numerical issue Réza observed in a simulation with an AnalyticNonGaussian PSF but not in a simulation with a MappedFromFile PSF. I was not able to recreate such an artifact by simply switching from a MappedFromFile PSF to an AnalyticNonGaussian PSF, so unfortunately I have no idea about the cause.

**Comment by drsamadi** [comment]
Hi Carsten
ok thanks for your feedbacks. Beside a possible error from my part, it could also be a version isuse. I'm working with PlatoSim 3.3.6-181-ga79d056
Can you make your two simulations available ?  Thanks !
Réza

**Comment by carstenpaproth** [comment]
Hi Réza,
I did the quick test with PLATOSim 3.3.7-52-g457ffa7. I used my experimental yaml file with all effects deactivated except the jitter. Then I made one simulation with MappedFromFileAsymmetrical and one with AnalyticNonGaussian. For the photometry, I added the middle 2x2 pixels for every imagette, but I couldn't see such a numerical issue which looks like a quantization artifact. Maybe, the problem comes from the photometry?
Carsten

[inputfilenew.yaml.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/4609976/inputfilenew.yaml.txt)

[star18.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/4609964/star18.txt)

**Comment by drsamadi** [comment]
Hi Carsten, 
I don't think that this comes from a bug related to the photometry extraction. I use aperture binary masks, and so this is difficult here to do a mistake ; any mistake would have big impact on the light-curve (LC).
In my case the aperture masks are different despite the fact that the star has the same magnitude. The procedure to define the mask and compute the photometry are the same for both data sets.

In the second set (MappedFromFile), the mask is however smaller. This is explained by the fact that MappedFromFile PSF contains chromatic aberration, as a consequence the centroid of the PSF is not in the middle of the PSF matrix. On the other hand the Analytical PSF are centred. In both data sets, I setup the star to be at a pixel corner,  however because of the chromatic aberration, the star of the second set is located close to the pixel center and accordingly the mask smaller than for the first data set (Analytical PSF).

To check the two data sets in a consistent way I compute the photometry using the same mask. The mask is now square, has a size of 4x4 and is centred around the star. 
The LC associated with the first set is the following:
![Figure_1](https://user-images.githubusercontent.com/19569211/81650977-a7a36380-9432-11ea-905a-06a013f60b1c.png)
while this of the second set looks like this:
![Figure_2](https://user-images.githubusercontent.com/19569211/81650997-ab36ea80-9432-11ea-90e7-e2fc44c13712.png)

I suspect that the difference can still be explained by the existence of the chromatic aberration in the second data set, indeed  the star being in the middle of the pixel it can never be perfectly centrered with a 4x4 mask and hence is more sensitive to the jitter noise. 
Having a mask of size 6x6 makes the photometry almost insensitive to the jitter noise . 
In that case the LC  of the second set becomes likes this:
![Figure_2_6x6](https://user-images.githubusercontent.com/19569211/81655976-ee935800-9436-11ea-9116-475a04bf2ce8.png)
while this of the first set:
![Figure_1_6x6](https://user-images.githubusercontent.com/19569211/81656010-f6eb9300-9436-11ea-8ca6-34b2c4f0e23d.png)
In that case both LC show a noise that is very likely due to the quantification noise (the jitter being now negligible for both LC).

What do you think about this interpretation ?

Réza

**Comment by carstenpaproth** [comment]
Hi Réza,
Now I understand, I had to use a broader mask for the photometry and I had to turn on the quantization in PLATOSim to get a similar quantization artifact, but it is actually not dependent on the PSF method used. I think, we just see the 25 electrons per ADU, so it is not a bug, but there could be a rounding bias?
Carsten

**Comment by drsamadi** [comment]
Hi Carsten
yes absolutely this is not at all a bug but just  quantization noise. Thanks for double-checking this and sorry for wasting your time. 

I'm happy because I'm now able to infer the star displacements at the cadence of input jitter file. This is required for performing the jitter correction (which will be required if the jitter turns out to be much bigger than the specifications) . 

I will then close the issue. 
Réza
