### ISSUE TITLE
Solar panels should face Sun directly in the middle of the quarter (not at the start)

### ISSUE THREAD

**Issue by SaraRegibo** [IvS-KULeuven/PlatoSim3#487]
Currently we set the orientation angle of the solar panels to 0°/90°/180°/270° at the start of Q1/Q2/Q3/Q4.  As a result, the solar panels will be facing the Sun directly **at the start of each quarter**.  In reality, however, the roll at the start of each quarter should be such that the solar panels are facing the Sun directly **in the middle of the quarter**.

As a consequence, the value of the solar-orientation angle at the start of the quarters (`sim["Platform/SolarPanelOrientation"]`) should be -45°/45°/135°/225° (instead of 0°/90°/180°/270°).

**Comment by JorisDeRidder** [comment]
Additional info: issue reported by Martin Pertenais (DLR).

Although the reported issue is correct, changing the current behavior does not give any added value.  The point of the orientation angle of the solar panels is to be able to enforce a change in roll every quarter, so that the stars change their position on the CCD which is visible as a jump in the lightcurve.  The exact initial roll angle does not have any effect on the simulated lightcurves. This may change if we ever implement the effect of straylight.

**Comment by SaraRegibo** [comment]
- the orientation angle of the FP / CCD on the sky will also be different (45°) → this will hardly change the LC, but it will change the content of the full-frame images;
- the source will land on a different part of the CCD (or potentially even on a different CCD):
     - different position → different PSF (which might actually also have an effect on the LC);
     - different CCD → different CCDs will have different characteristics + depending on on which CCD the source lands, it will be "seen" by more/less camera groups (with different characteristics).

**Comment by nicholasjannsen** [comment]
At this point in the mission where we exactly know `{alpha, delta, kappa}` for the LOPS2 and LOPN1 this is not relevant any more. E.g. the "realistic" use case of PlatoSim for the exact observing mode of PLATO (i.e. multi-quarter simulations), we should: 1) refer to either PLATOnium (for which these angles are correctly set for each quarter), or 2) the user should create a script that correctly will set `kappa` (i.e. the solar panel orientation) corresponding to the middle of the mission quarter.
