### ISSUE TITLE
Need for new distortion file

### ISSUE THREAD

**Issue by SaraRegibo** [IvS-KULeuven/PlatoSim3#498]
The files with the distortion coefficients (`inputfiles/distortioncoefficients.txt`) and inverse distortion coefficients (`inputfiles/distortioninversecoefficients.txt`) are outdated (they correspond to an old implementation of the field distortion): they both comprises five columns instead of four (time, `k1`, `k2`, `k3`).  @denisGrBach, could you generate new files, please?  Could you then also provide me with a short description of the files to include in TN6?  Thanks!

**Comment by denisGrBach** [comment]
The files are derived from cameraloop2b data and contain the timestamp and 3 radial-symmetric distortion parameters [t, k1, k2, k3]. Since the thermal simulation uses some worst case realization of the optic design, it does not reflect the nominal behaviour. 

[cl2bDistortionInverse.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/5073097/cl2bDistortionInverse.txt)
[cl2bDistortion.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/5073098/cl2bDistortion.txt)

**Comment by nicholasjannsen** [comment]
@Dries-Seynaeve this has been implemented into the Wang model (for Analytic PSFs) right?

**Comment by Dries-Seynaeve** [comment]
Yes, I believe so. I'll close the Issue.
