### ISSUE TITLE
Star flux as a function of the star incidence angle

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#500]
Hi,
I simulated a full image using as input a catalogue build from the Gaia catalogue. 

In the HDF5 the record named 'StarPostions'/'flux'  corresponds  to the "number of photons of those stars that got detected in the sub-field during the exposure" (according to the online documentation(http://ivs-kuleuven.github.io/PlatoSim3/OutputFileDescription.html) 

Then I have plotted the quantity F = flux * 10**(+0.4 * Mag) 
I was expecting something decreasing as  1 / (cos(theta))**2 where theta is the angle between the star and the optical axis (the star incidence angle) or something flat if the natural vignetting is not yet taken into account in 'flux'.  But I get such such a plot:

![Figure_2](https://user-images.githubusercontent.com/19569211/93346423-418d7980-f834-11ea-84e2-bdfc0789b5f6.png)

I don't understand neither the dispersion nor the strict upper  limit. 

Therefore I have some difficulty to interpret this result. Do someone as an idea ? Did I miss something?

**Comment by JorisDeRidder** [comment]
Just to check that I properly understand the problem. Your input catalog was derived from the Gaia catalog. Did you use any hard magnitude limits for your input catalog that could explain the strict upper limit? Your stars have all different magnitudes (and thus intrinsic fluxes), right? Do you still don't see the cos(theta)^2 dependence when you limit yourself to stars within a narrow magnitude range?

**Comment by drsamadi** [comment]
Hi Joris,
I've limited my input catalogue to star brighter than exactly 18 (strict limit).

Here the same quantity F as a function of the magnitude:
![Figure_4](https://user-images.githubusercontent.com/19569211/93354025-db592480-f83c-11ea-926f-00c741173491.png)
This plot shows that the upper limit is not connected with my limiting magnitude (18).

I have below over plotted in red stars in the magnitude range 8 - 9 but I do not see the expected decrease with 1/ cos(theta)^2 

![Figure_2](https://user-images.githubusercontent.com/19569211/93354848-c29d3e80-f83d-11ea-8839-9afe54634864.png)

The same plot with only the stars in the magnitude range 8-9
![Figure_3](https://user-images.githubusercontent.com/19569211/93354925-d2b51e00-f83d-11ea-96e3-c5e6b67ca7c5.png)

All these plots suggest that 'flux' does not yet account for the natural vignetting right ? However the dispersion and the strict upper limit are not clear me.

**Comment by JorisDeRidder** [comment]
The fact that no natural vignetting can be seen is normal. The fluxes per exposure written to the HDF5 file contain the transmission efficiency and the light collecting area of the telescope, but not yet the vignetting. That is only implemented in a later step on pixel level (because stars are spread out over several pixels).

I also don't understand the hard upper flux limit, because this should be different for each angular distance bin. I'm also really suspicious about the fact that a V=2 and a V=18 star hardly differ in flux. That can't be right. 

Is there a way for you (e.g. [WeTransfer](https://wetransfer.com/)) to send over the input file and the scripts you use to make the plots? This would be helpful for us to dive deeper into this.

**Comment by drsamadi** [comment]
Given the fact that I compute and plot the quantity f = flux*10**(+0.4 *mag) and given the fact that flux does not account for the vignetting, all stars should have the exactly the same f values.
You should receive by email a link for downloading the HDF5 file. Below are the python commands used to generate the first plot. 

In [4]: F=h5py.File('01.hdf5')
In [12]: y = np.array(F['StarPositions']['Exposure000000']['yFPmm'])
In [13]: x = np.array(F['StarPositions']['Exposure000000']['xFPmm'])
In [14]: flux = np.array(F['StarPositions']['Exposure000000']['flux'])
In [17]: mag = np.array(F['StarCatalog']['Vmag'])
In[18]:  f0 = flux * 10.**(0.4*mag)
In [19]: fl  = 0.24752 * 1000.0 # focal length in mm
In [20]: theta = np.arctan( np.sqrt(x**2 + y**2)/fl)
In [42]: plot(theta*180./math.pi,f0,'k.')

**Comment by JorisDeRidder** [comment]
Ah OK, I read over the 10**(+0.4*V) somehow. I looked deeper into our code, and I found the reason for your plot results. The reason is that we floor() the photon flux (i.e. to an integer number of photons). that is:
`flux = floor(fluxFactor * pow(10.0, -0.4 * Vmag) * timeStep);`
Removing that floor() function gives indeed a flat (constant) flux * 10**(+0.4*V) value independent of the angular distance of the optical axis.

**Comment by drsamadi** [comment]
I was suspecting some numerical issues, now the strange curve is explained. Thanks for your clarification Joris!

**Comment by drsamadi** [comment]
By the way Joris, I have another question related to the star incidence angle. Is this angle calculated using the distorted or un-distored star focal plane position ?
In principle one should consider the un-distored FP position, however, simulations made with PLATOSim seam to show that distorted FP positions are used. Can this be checked ? Thanks.

**Comment by JorisDeRidder** [comment]
The incidence angle (used to compute e.g. vignetting) is always computed using the **un**distorted focal plane coordinates. 
Assuming that "Camera: IncludeFieldDistortion" is set to yes in the yaml inputfile, the focal plane coordinates saved in the HDF5 file are the distorted ones.
