### ISSUE TITLE
Question about SkyBackground value in platosim hdf5 output file

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#505]
Hi,

I was wondering how the background value of platosim hdf5 output is computed ?

For example, with the input file attached ([0000013120.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/5341542/0000013120.txt) containing standard values), I get a background value of 4691.0 within the background dataset of the hdf5 output file.
What is the unity, e-/pixel/exposure ?

When I look at the code, I find the following computation for the background value:

camera.cpp : 771
```
     totalSkyBackground = floor(userGivenSkyBackground * exposureTime * transmissionEfficiency);`
342 * 21 * 0.7821
```
Detector.cpp:2437
```
       skyBackground = camera.getTotalSkyBackground();

       skyBackground *= expectedValueRelativeTransmissivity;
0.92
        skyBackground *= expectedValuePolarization;
0.989
        skyBackground *= particulateContaminationEfficiency;
0.972
        skyBackground *= molecularContaminationEfficiency;
0.9573
        skyBackground *= meanQE * meanAngleDependencyQE;
0.5985 * 1.01
```

hence
>>> 342 * 21 * 0.7821 * 0.92 * 0.989 * 0.972 * 0.9573 * 0.5985 * 1.01
2874.6

So I was expecting 2874 when I got 4691, may you explain this computation ? 
We need the true background values used to build imagette in order to apply our preprocessing algorithm after platosim.

Thanks

**Comment by JorisDeRidder** [comment]
Hi,

The background value saved in the HDF5 file is expressed in photons/pixel/exposure. It's the background flux right before it hits the CCD, and is indeed computed with `userGivenSkyBackground * exposureTime * transmissionEfficiency`. In your particular example: 342 * 20.973474 * 0.8135 (BOL) = 5835 ph/pix/exp. This is also what I get when I run PlatoSim. 

If I understood you correctly, you would like to have a background value expressed in electrons/pixel/exposure. How exactly do you define this value? Because of the dependence on the incidence angle, the background value varies over the subimage. Would a mean background value be sufficient for your purpose?

**Comment by manugr788** [comment]
Thank you Joris, 
I see more clearly now, so it means that Platosim applies a background value which is different for each pixel regarding the incidence angle on the pixel, is it correct ?
In the code I only see the formula reagarding the QE:  `skyBackground *= meanQE * meanAngleDependencyQE; (Detector.cpp:2437)`,
so what is the applied formula to take into account the dependence on the incidence angle ?

If the applied background is pixel dependent (it is true in real life indeed) we may need to have a background pixel map (in e-/exposure) for each exposure, but I let @drsamadi give his opinion, do we really need this, or if a mean of subfield background may be enough.

**Comment by drsamadi** [comment]
Hi,
the recent version of PlatoSim now provides an efficiency map, then from it we shall be able to compute the background for each pixel for instance like this:
  userGivenSkyBackground * exposureTime *  EfficencyMap[x,y]
where x and y is the pixel location. In principle the background added to the image/imagettes should take the  Efficency Map into account, excatly as this is done for the stars, right? 

The background will indeed change across the FoV, not only because of the dependence of the vignetting and Quantum efficiency  on the incidence angle but also because the Zodiacal light significantly varies across the FoV. This said, the background is not expected to vary significantly over our nominal 6x6  imagettes.  In practice, spatial variation of the background will only matter when we will process full images.

**Comment by JorisDeRidder** [comment]
Hi,
Réza is correct, with a slight modification:

`skyBackground [e-/pix/exposure](row, col) = userGivenSkyBackground [photons/pix/s] * exposureTime * transmissionEfficiency * throughputMap(row, col)`

The transmissionEfficiency is stored in the HDF5 file in the folder `TransmissionEfficiency` (it may change from BOL to EOL), the throughput maps in the folder `ThroughputMaps`. 

If you like to use `simfile.py`, a throughput map can be simply retrieved using e.g. `getThroughputMap(2)` for the throughput map of the 3rd exposure.
