### ISSUE TITLE
Jitter is inconsistent between CCDs when simulating multiple times with setSubfieldAroundCoordinates

### ISSUE THREAD

**Issue by Caykroyd** [IvS-KULeuven/PlatoSim3#508]
I have run into unexpected behaviour when simulating jitter for multiple stars in different CCDs.

I have a script which runs the simulation once for each guide star, for the Fast Cameras. The script is based on the jupyter notebook found in [FineGuidanceStarsExample.ipynb](https://github.com/IvS-KULeuven/PlatoSim3/tree/develop/docs/tutorials/FineGuidanceStars/FineGuidanceStarsExample.ipynb)

Whenever I use the "setSubfieldAroundCoordinates" function (present in simulation.py), the ACS Jitter seems to behave unexpectedly. In particular, stars falling on distinct CCDs do not have similar ACS Jitter curves, as can be seen in the image attached below. I'd expected the jitter to be the same regardless of the CCD, since if I understood correctly, the angles are w.r.t Platform coordinates.

I generate the jitter from Red Noise (using the same seed), and later extract it from the hdf5 file through means of the "getYawPitchRoll" function.

As can be seen from the image, three of the curves are similar (but not identical, as I would expect), whereas the jitter for the fourth CCD is completely different.

![jitter](https://user-images.githubusercontent.com/19802342/96933656-3e228900-1497-11eb-89ee-454865e89363.png)

I'm attaching a [script](https://github.com/IvS-KULeuven/PlatoSim3/files/5426178/script_minimal.zip) with the minimal code to reproduce the issue, along with the input yaml and catalogue used as an example. The script can be run by keeping all three (.py file, .yaml and catalogue) in the same folder.

## System Details:

Ubuntu 18.04.5 LTS

PlatoSim version: v3.2.0-RC1-1032-g4b7e85d

Gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

Cmake version 3.10.2

Python v3.8.2

**Comment by Dries-Seynaeve** [comment]
Hello, there was some inconsistency in how the jitter was implemented at the first exposure. I believe the most recent version at the develop branch should fix this. 

The jitter as a function of time should now behave similarly for the different CCDs.

**Comment by Caykroyd** [comment]
Hi,

Thank you very much for your help. Indeed, I re-simulated the graph and the jitter now looks more like expected. However, I noticed there is still some slight offset; 

In the plot below, generated from RedNoise, we can see a small shift between the curves. I believe this might be due to some rounding artefact of the CCD time-shifts. Notice that the time shifts are respectively, **[0.0, 6.25, 12.5, 18.75]**. We can see that, in the plot, CCD 1 and 3 have similar behaviour. Likewise for 2 and 4. Can this be related to how the red-noise is sampled?
![platosim_CCDs_rednoise_FC](https://user-images.githubusercontent.com/19802342/116738012-47515d00-a9c8-11eb-9655-27bc5abcd66c.png)

**Comment by Caykroyd** [comment]
As an additional note, I also made another simulation using the jitter angles supplied by OHB. In this file, the input jitter starts at 250 seconds. This means that to be able to use the file, I need to offset the starting jitter. However, the custom CCD time-shift I had set does not affect CCDs 1 to 4 (or 1F-4F). 

This was confusing me because I was getting the plot below:
![platosim_CCDs_OHB_FC](https://user-images.githubusercontent.com/19802342/116739875-95676000-a9ca-11eb-8e47-4db99bb3d9cd.png)


For it to work, I have to change the hardcoded chunk of the yaml, where it explicitly says,
`# ----- DO NOT MAKE CHANGES BELOW THIS LINE -----`
and set the CCD timeshift to
`TimeShift:                       [250.0, 256.25, 262.5, 268.75]`
After adding the time-shift, it works exactly as expected.
![platosim_CCDs_OHB_FC_TS](https://user-images.githubusercontent.com/19802342/116739718-63ee9480-a9ca-11eb-95cc-56077029962a.png)

To conclude, I thought it might be interesting to consider adding a global offset to the actual jitter file settings.

Thanks again

**Comment by Dries-Seynaeve** [comment]
Hello
This is a bit longer answer than strictly necessary, but this might be useful when dealing with simulations with jitter. 


1. The shift you mentioned is caused by the fact the CCDs are not read out at the same time. The reason that CCD 1 and 3 have similar behaviour is because these two CCDs are read out at the same time. They start respectively at time 0 and 12.5 so after 5 exposures (given that it takes 2.5s for one exposure) they will read the jitter at the same time. The CCD 2 and 4 starts at time 6.25 and 18.75 and so they will also read out jitter at the same time. However, there will be a time difference of 1.25s between CCD 1 (or 3) and CCD 2 (or 4). This is because a new Yaw, Pitch and Roll is generated once for every exposure since the Jitter time scale is large (this can be set in [Platform/JitterTimeScale] in the input yaml file). You should be able to get rid of this by making sure the simulator generated a new Yaw/Pitch/Roll at the same time for every CCD. In this case, I believe this would work if you set sim["Platform/JitterTimeScale"] = 12.5. (In this case, a new Yaw/Pitch/Roll will be generated every 1.25s)

To illustrate this point a bit further, I have made a similar plot as yours but with normal cameras that have an exposure time of 25s, for 3 exposures. I have set the [Platform/JitterTimeScale] to 25, so jitter will be generated every 2.5s. I plotted the jitter for the 4 CCDs as discrete points and also plotted the jitter for CCD 1 as a step function, with the length of every step 2.5s. We would expect the jitter of all the CCDs to fall onto this step function. Outside the grey regions, this happens without any problems. Inside these grey regions is where CCD 1 is read out, and no new jitter is "seen" by CCD 1 in this step. This is why in these regions the jitter does not seem to match the step function. 


2. I think for the simulation you mentioned, it might be better to set sim["ObservingParameters/NumExposures"] = 100. I think this should have the same effect.

I hope this helps, if you have any other/further question, I am happy to help.
[jitterOnCCDs.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/6416176/jitterOnCCDs.pdf)
