### ISSUE TITLE
PlatoSim version number

### ISSUE THREAD

**Issue by denisGrBach** [IvS-KULeuven/PlatoSim3#554]
I was wondering what is the best way to refer to a specific PlatoSim version. I’m on the development branch and with “git describe develop”, I get “v3.2.0-RC1-1419-…..”. This might be the latest tag but also there is a release 3.3.7. on the master from exactly 1 year ago. I would expect something >3.3.7.

**Comment by rhuygen** [comment]
I think the best way to report your version is to use the following command (the output is from my current installation):
```
$ git log --pretty=format:'%ad %h %d' --abbrev-commit --date=short -1
2021-02-25 244504b  (HEAD -> develop, upstream/develop)
```

**Comment by SaraRegibo** [comment]
An alternative is to use (annotated) tags, which provide a more verbose description on what was included in the last PR.  I would not tag every change to the develop branch (e.g. not for correcting typing mistakes, formatting code, etc.) but only for changes like:
- introduction of new features;
- bug fixes.

**Comment by rhuygen** [comment]
Using annotated tags is a good idea for releases, but if a user works with a development release and updates with git fetch/merge or git pull, then you still want to know which commit (s)he is running, depending on the bug report of course.

**Comment by denisGrBach** [comment]
I think, 'git describe' can do both. You get the tag (human readable), the additional commits since that tag (thats the 1419 in my initial comment) and the abbreviated object name for the commit itself. The tag would make it easier to see immediately where you are and you can go back to the specific commit if needed.

**Comment by JorisDeRidder** [comment]
I'm trying to establish if there still is a problem, or whether we can close this issue. Currently `platosim --version` gives you the latest tagged version, together with the commit hash. For example: `PlatoSim 3.4.0-1-g9d41e0a`. Under the hood PlatoSim uses `git describe --tag` which uses not only the annotated tags but all tags found in the refs/tags namespace. We do need to take care that tags are pushed to both the develop and the master branch so that no inconsistencies appear, when using `./platosim --version`. Is this sufficient for you, @denisGrBach ?

**Comment by denisGrBach** [comment]
ok, `git describe --tag` gives a resonable result for the development version I use in the moment. I guess this solves the issue, thanks.
