### ISSUE TITLE
"quantisation was applied but pixel map values are not in [0,2^16["

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#584]
Hi ,  
We get the message "quantisation was applied but pixel map values are not in [0,2^16[
which we didn't have previously. The only changed made in the YAML file (here attached ) is to turn off the following parameters:

  IncludeDarkSignal:               no              # Include dark sign al non-uniformity [yes or no]
  IncludePhotonNoise:              no              # Include photon noise [yes or no]
  IncludeReadoutNoise:             no              # Include readout noise [yes or no]
  IncludeOpenShutterSmearing:      no              # Include trails due reading out with an 

do someone has an idea why I get now such an error message ?

Note that this simulation (n-cam fullframe) does include background (=0) 

Réza

PlatoSim 3.3.7-462-g8177ec0

[CCD1_SFP.yaml.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/6440331/CCD1_SFP.yaml.txt)

**Comment by drsamadi** [comment]
Note that very strangely the error disappear when one turn off the BFE . 
Furthermore, it does not occurs when there is no stars in the FoV or also when the image is smaller (tested with 500x500 images and 1000x1000 images ).

**Comment by drsamadi** [comment]
Interestingly also, the error does not show up as soon as the photon noise is included.

**Comment by Dries-Seynaeve** [comment]
Hello. 

The issue seemed to be caused by the current implementation of the BFE. If there are very large charges in a pixel, and very small values in the pixels around them the current approximation of the BFE subtracts more charge in that pixel than there was in the first place. Because of this, the pixel map had negative values.  I now applied the flooring before applying the BFE, so there won't be any pixels with too much charge in them. Let me know if this fixes the issue. 

Kind regards 
Dries

**Comment by drsamadi** [comment]
Hi Dries,
thanks for your feedback. What do you mean by 'flooring'  and by 'very large amount of charges' ? Obviously a pixel can contain up to its full well capacity (~ 1 millions e-). 
Réza

**Comment by Dries-Seynaeve** [comment]
Hello Réza

Instead of 'flooring', I should have used 'full-well saturation'. 

In the way this was implemented before, the full well saturation happened  after the BFE. So at that point a pixel could have had more then the full well capacity allowed. If a pixel has a charge that is higher than around ~10^8 e- , the current BFE implementation subtracts more charge from that pixel than is available.  Which is why you had this error, since the pixel map contained negative values after applying BFE. 
Now we first apply full well saturation, so these large values (> 10^8 e-) don't occur. 

Kind regards 
Dries

**Comment by drsamadi** [comment]
OK, thanks for the clarification and indeed these changes make sense. Have the changes been pushed into the  development branch ?

**Comment by Dries-Seynaeve** [comment]
Yes, these changes should now be in the develop branch.

**Comment by drsamadi** [comment]
OK we did a check and now we do no longer get the error. thanks
