### ISSUE TITLE
hdf5ToFits -- string conversion

### ISSUE THREAD

**Issue by PierreRoyer** [IvS-KULeuven/PlatoSim3#600]
Hi,

I get the following error message when converting hdf5 to fits (the resulting fits file is incomplete):

```
>>> hdf5ToFits(hdf5_filename, fits_filename)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/pierre/plato/platosim/python/platosim/hdf5ToFits.py", line 65, in hdf5ToFits
    if simFile.getInputParameter("CCD/ReadoutMode", "ReadoutMode").decode("utf-8") == "Nominal":
AttributeError: 'str' object has no attribute 'decode'
>>> print(sim["CCD/ReadoutMode/ReadoutMode"])
Partial
```

I'm simulating partial readout (3 frames, 2295x400).

**Comment by SaraRegibo** [comment]
The problem is that `simFile.getInputParameter("CCD/ReadoutMode", "ReadoutMode")` returns a `str` for Pierre and a `bytes` for me.

**Comment by Dries-Seynaeve** [comment]
Hello Pierre, 

I believe this should have been solved with the latest commit. Let me know if this works for you.

**Comment by SaraRegibo** [comment]
Why is the result of `simFile.getInputParameter("CCD/ReadoutMode", "ReadoutMode")` in some cases a `str` and in other cases a `bytes`?

**Comment by JorisDeRidder** [comment]
@PierreRoyer and @SaraRegibo : could you give us the Python and the PlatoSim version you are using? And whether you used conda to install PlatoSim, or whether you built it manually from a GitHub clone?

**Comment by SaraRegibo** [comment]
In an attempt to update `h5py` (because I thought it could have to with that - Pierre had a more recent version), I messed up my Conda environment (the update messed up `numpy`), unfortunately (so I might not be able to provide you with all the info you need).  I was using:

- Python 3.6;
- GitHub installation of PlatoSim;
- `h5py` 2.9 (if I remember correctly);
- Latest version of the code before this fix.

For completeness, I am now using Python 3.9 (and `h5py` 3.2.1), and the result of `simFile.getInputParameter("CCD/ReadoutMode", "ReadoutMode")` is now `str` (as I would expect).

**Comment by Dries-Seynaeve** [comment]
Hey, 

It seems that way that h5py stores and reads string has changed since version 3.0. So I agree with Sara that this is likely the cause for this discrepancy.
