### ISSUE TITLE
F-Cam implementation

### ISSUE THREAD

**Issue by Dries-Seynaeve** [IvS-KULeuven/PlatoSim3#605]
When simulating an entire CCD with F-Camera, the entire CCD contains stars while only half of the CCD should contain them since the other half if physically shielded off.

**Comment by Dries-Seynaeve** [comment]
Hello Réza

I have changed the way PlatoSim selects the subfield from the input parameters. For F-Cams, ~~the subfield will now only consist of the parts that are exposed. If no part is exposed, the simulation will not run and an error will be generated.~~ Let me know if this works for you or if you would like additional/other changes.

**Comment by drsamadi** [comment]
Hi Dries
I have tested the latested version (3.4.0-91-g6a6add2), its behaves now as you describes ; however the generated images is not yet compliant with that we expect:
The last 5 rows of the second half of the CCD are covered, and should then not contain stars. They are read to characterize  the smearing.
 Finally we will have 10 additional lines. 5 of them are over-scan rows and the last 5 ones are lines obtained by reading the contain of the register without doing line transfers 
Also the first 5 columns and the last 5 columns are covered, therefore thye should not contain stars.
For more deails see Juan's presentation here attached, in particular slide 10.

Unless I'm wrong the images currently generated by platosim (for a f-cam) do not yet full fill all those features,am'I right?  

Cheers,
Réza

[F-FEE_CCD_clocking_20210531.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/7185576/F-FEE_CCD_clocking_20210531.pdf)

**Comment by drsamadi** [comment]
Another question related to the f-cam: I have seen that there is the new input file  "apsf_N6000K_v2.txt" which contains
new analytical PSF model, I guess for the N-cam ?
Are they  equivalent input files for the f-cam  ? (i.e. with decofused PSFs for both the blue and red filters)

**Comment by carstenpaproth** [comment]
@drsamadi 
Hi Réza,

Yes, apsf_N6000K_v2.txt is the new set of parameters for the new analytical PSF model. It is for the nominal case only, N-cam with 6000K star and in focus.
There are no special parameter sets for the F-cams, defocus, or different star temperatures.
I think it is better to use the sampled ZEMAX PSFs for special cases as the analytical PSF approximation often has some deviations to the sampled PSF which can be larger than the differences between the sampled PSFs, e.g. the change from 5000K to 6000K is smaller than the difference between the anlytical 6000K PSF and the sampled 6000K PSF. So if you are interested in some small scale change in the PSFs, then the analytical PSF model is probaly not the right model as it doesn't capture these small scale changes well.
If there is a strong demand for special parameter sets for larger scale deviations, e.g. red and blue F-cams, then I can create such sets. It took about 2 weeks to derive the apsf_N6000K parameter set, but I am still not completely happy with the result.

Cheers,
Carsten

**Comment by Dries-Seynaeve** [comment]
Hello Réza, 

You are correct that PlatoSim doesn't currently has all these aspects for the F-Cams. Getting a more complete implementation for the F-Camera is our next TODO item. 

Kind regards 
Dries

**Comment by drsamadi** [comment]
Hi 

ok thanks Dries,  let me know when those features will be implemented. 
Carsten, thanks for your feedback. Although this is much slower,  I will then consider "MAPPED from file PSF".  Do you have the HDF5 files corresponding to the f-cam (blue and red filters) ? 

Réza

**Comment by carstenpaproth** [comment]
Hi Réza,

I think @denisGrBach can provide such HDF5 files.
If you want to investigate the precise difference between the red and the blue F-cams, then it makes most sense to use the mapped PSF to avoid deviations coming from the analytical PSF approximation. If the precise behavior is not that important, the apsf_N6000K parameter set could still be used for faster F-cam simulations.

Cheers,
Carsten

**Comment by drsamadi** [comment]
Hi Carsten,
thanks for your answer. OK will contact Denis. 
Do you know if the f-cam PSFs are still defocused, I'm not sure ?
If so and if I use the file  apsf_N6000K parameter the problem is that those PSFs are  fosused and therefore will not be sufficiently representative for the f-cam.
Cheers,
Réza

**Comment by carstenpaproth** [comment]
Hi Réza,

If I remember correctly, the idea was that with a defocused PSF the PSF will get more Gaussian-like and thus the FGS could calculate better centroids, but the defocused PSF turned out to be not more Gaussian-like, so the F-cams are not defocused. But I'm not sure, maybe Denis can clarify.

Cheers,
Carsten

**Comment by denisGrBach** [comment]
Carsten is right, defocused PSFs doesn't improve the FGS. The PSFs are not necessarily getting more Gaussian but only more spread out which decreases the SNR. Check the latest FGS performance report for more details.

**Comment by drsamadi** [comment]
Hi Denis, Carsten
thanks for the clarification. Denis uou should have received by email my request for the HDF5 PSF files for the f-cam. 
I have run a microscanning simulation for a single star observed with the f-cam and using a sampled Zemax PSF but the computation time is very long: 1h30 on my laptop!
For some application this can be very problematic.

In addition to their speed, the other advantage of the analytical PSFs is that their parameters change continuously across the focal plane (if I'm correct).
Of course the analytical PSFs do not capture the small scale structures, however I believe that the latter tend to disappear  with the charge diffusion.
 Therefore, since the f-cam PSFs are not going to be intentionally defocused and since the color effect is according to Carsten already smaller than the difference btw the sampled PSF and the analytical one, I think it makes sense to use the file  apsf_N6000K_v2.txt in f-cam simulations.

Réza

**Comment by carstenpaproth** [comment]
Hi Réza,

Yes you are correct, the analytical PSF changes continuously across the focal plane. And yes, I think apsf_N6000K is sufficient for F-cams in most cases as the approximation error is quite large, charge diffusion reduces differences between PSFs, and the real PLATO PSF will differ anyway. And if it is not sufficient for a specific case, the mapped PSF can be used instead.

Cheers,
Carsten

**Comment by drsamadi** [comment]
Hi Denis
the HDF5 PSF files you gave to me recently are no longer compatible with the current version of  platosim. 
According to Dries, platosim requires the presence in the HDF5 of a field named 'Coordinates map' that contains both the  undistorted and distorted  coordinates. See:   https://github.com/IvS-KULeuven/PlatoSim3/issues/627#issuecomment-925902409
Do you plan to add them in the HDF5 ? 

Réza

**Comment by manugr788** [comment]
Hi,
I tried to simulate a full-frame image for F-CAM (every rows but only 1000 columns). I used Platosim 3.5.2-6-g10382940. It seems that F-CAM features have been well implemented in this Platosim version. I saw some fields in the yaml configuration file relevant for F-CAM properties.

```
GroupID:                         Fast  
…
FirstRowForFastCamera:           [2255, 2255, 2255, 2255]       # Only the upper half of the CCDs is active/illuminated for the Fast Camera's
        IncludeMetallicShield:            yes                        # Whether or not to include a metallic shield for fast camera
        ShieldColumnCoordinates:         [10, 4500]                 # First and last column of CCD that isn't covered by metal shield around fast camera [pxl]
        ShieldRowCoordinates:            [2260, 4505]               # First and last row of CCD that isn't covered by metal shield around fast camera [pxl]
```

Moreover, I saw Dries message above, saying that “_I have changed the way PlatoSim selects the subfield from the input parameters. For F-Cams, the subfield will now only consist of the parts that are exposed._” So I tried:
```
SubField
ZeroPointRow:                   0            # 2250 # Row of the (0,0) pixel of the subfield [pixels]
ZeroPointColumn:             0               # Column of the (0,0) pixel of the subfield [pixels]
NumColumns:                   1000               # Number of columns, should be >= 8 [pixels]
NumRows:                         2260     # Maybe 2245 was enough, but just to try what happen after row 4505
```

I got stars within my CCD using the starcatalog.txt and RA=182, DEC=-74 **but I am a little bit confused since all the stars since to be like a pack at the centre of the CCD. Did I do something wrong?**
Maybe I need to change other fields within the yaml file to run a realistic F-CAM simulation ? I used AnalyticNonGaussian with apsf_N6000K_v2.txt.

```
ObservingParameters:

    MissionDuration:                 6.5             # Total duration of the mission [yr], relevant for BOL->EOL degradation
    NumExposures:                    1              # Number of exposures
    BeginExposureNr:                  0              # Sequential number of first exposure. useful for slurm parallellisation
    CycleTime:                       2.5              # Image cycle time (exposure + readout before next exposure starts)[s]
    RApointing:                      182             # Platform (not telescope) right ascension pointing coordinate      [deg]
    DecPointing:                     -74             # Platform (not telescope) declination pointing coordinate          [deg]
    Fluxm0:                          1.00179e8       # Photon flux of a V=0 G2V-star                                     [phot/s/m^2/nm]
    StarCatalogFile:                 inputfiles/starcatalog.txt
```
[0000032165.yaml.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/8034738/0000032165.yaml.txt)

![fcam_simu](https://user-images.githubusercontent.com/12544881/153253386-1aaf1a98-01ea-4383-86b7-b20b6793fd7a.JPG)

**Comment by Dries-Seynaeve** [comment]
Hello, thanks for bringing this to our attention. 

Firstly, my previous comment about the subfield is no longer accurate. Now the subfield will be (again) the part of the CCD that is specified. We have gone back to this approach because the non exposed part of the CCD can stil feel bleeding from nearby exposed pixels. So it can be useful to still simulate these parts. 

Secondly, F-camera can only be simulated when the CCD position is not "Custom", I will later add a "CustomFast" option as well to simulate a F-cameras with a custom CCD, but for now the CCD position should be 1, 2, 3 or 4. I was will edit the inputfile to reflect this, since this is not obvious at all. 

Kind regards 
Dries

**Comment by manugr788** [comment]
Hi Dries,
Do you have an example of inputfile-fcam.yaml for F-CAM which works with starcatalog.coo ?
It will be very helpful if you can add this file to the inputfiles directory.

**Comment by Dries-Seynaeve** [comment]
Hello 

With my recent push, I included a custom input file for the F-Camera `inputfileFast.yaml`. I also changed the behaviour for Custom CCDs, so it is now possible to simulate F-Cameras with CCD set to Custom. 

I also changed the (default) starcatalog to one that is more in line with the PIC. This also means that the default pointing has been changed in the input files.  It is still possible to use the old starcatalog if anyone would like this, it is included as `starcatalogOld.txt` in inputfiles. But in order to observe these stars the ObservingParameters/RApointing, ObservingParameters/decPointing should be changed accordingly in the inputfile. 

Kind regards 
Dries

**Comment by manugr788** [comment]
Hi,
Thank you very much Dries, 
Just a few questions in inputfileFast.yaml
PlatoSim 3.5.2-14-gc0eba247

- is, line 155 "# REMARK: if Custom, then Camera/GroupID can not be Fast" an obsolete comment ?
- CycleTime: 25 , should not be 2.5 s  for Fast ?
- The first 5 rows (from 2255 to 2259) are not dropped but exist within the HDF5 output image with electronic offset only, am I right ?
- The last  5 rows (from 4505 to 4509) are opaque metallization and exist within the HDF5 output image with electronic offset only, am I right ?

Emmanuel

**Comment by Dries-Seynaeve** [comment]
Hello Emmanuel

Thanks for pointing these errors out, I have changed the input files accordingly.

You are correct that the first 5 rows are not dropped but simply covered by the metallic shield. I will implement this later, currently the covered parts of the subfield are all still included in the output hdf5 file. 

All the rows/columns that are covered by the metallic shield are not exposed to light, but they do feel all the other CCD effect. So to list a couple of examples:
- if a star would fall on a part of the CCD that is covered, this star will not be shown.
- if a star close to a part of the CCD causes blooming, that blooming can reach the covered part.
- the covered part will not be exposed to the background light
- cosmics can not fall onto the CCD part that is covered, they can however form a trail into the covered part

Kind regards
Dries

**Comment by manugr788** [comment]
Ok, everything sounds perfect now. I think you may close this issue.
Many Thanks,
