### ISSUE TITLE
MappedFromFileAsymmetrical: inconsistent PSF orientation 

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#627]
Hi
I have run a microscanning simulation  using a MappedFromFileAsymmetrical PSF.
After having running Daniel's inversion algorihm I get the following PSF
![Screenshot from 2021-09-23 12-30-24](https://user-images.githubusercontent.com/19569211/134492613-2a93e720-c837-45f3-b199-17a38a7d2587.png)
However the PSF stored in the platosim HDF5 in the field 'diffusedPSF' is oriented differently:
 
![Screenshot from 2021-09-23 12-30-43](https://user-images.githubusercontent.com/19569211/134492733-6e17db03-1941-4a93-a059-c0b06b8e7e73.png)

Therefore  there is no consistency between the inverted PSF and the true one in terms of orientation.

Note that the inversion algorithm derives the PSF as it seen on the imagette (i.e. in the CCD frame), and there is not error of orientation made by the inversion algorithm. Indeed, when I'm using AnalyticNonGaussian PSF, the inverted PSF and the PSF stored in HighResPSFmapCenterSubfield have consistent orientation.

Furthermore since my star is located in the middle of CCD2 (lower left part of the focal plane), the PSF should be oriented in a different way on the CCD. Indeed, at that location of the focal plane, the PSFs look as plane,. Accordingly,  in the frame of CCD2 the nose of the plane should be oriented in the opposite direction to the one shown in the first figure (the invert PSF wich is necessary oriented the way  the PSF is seen by the CCD2), that is its nose  should toward the bottom right of the image
(CCD2 frame). 

Réza
ps:
* PlatoSim 3.4.0-91-g6a6add2
*  MappedFromFileAsymmetrical = file given by Denis and named 'FT_-40mu_B6000K_700stars.hdf5' 
* star located on CCD2 at Xcc=2501, Yccd = 2510  Xfp =  -37.300 mm, Yfp = -46.479 mm

**Comment by Dries-Seynaeve** [comment]
Hello Réza

I suspect that this problem could be caused by two things: 

1. The diffused PSF is saved before applying rotation (due to the CCD orientation). Since the PSF is on CCD 2, the image should be rotated by 270 degrees counterclockwise. To get a better idea of the orientation on the CCD might be useful to compare this to 'roatedPSF' in the HDF5 file. 

2. I am not sure about how the file 'FT_-40mu_B6000K_700stars.hdf5' is obtained, but I remember that for the PSF files that I prepared for PlatoSim, the reference frame that was used was different from the one that we use in PlatoSim.  Practically this meant that we had to swap the xFP coordinates from the hdf5 files to use them in PlatoSim. Maybe something similar has happened here. 

As a small (unrelated) comment, for the mapped PSFs we now use a mapped distortion model. This is done by including a conversion table (from undistorted coordinates to distorted coordinates) in the mapped psf hdf5 file. You can inspect how this looks like from the psf files available on the [website](https://ivs-kuleuven.github.io/PlatoSim3/_reqs_run.html). If you want I would be happy to include such a conversion table for your file, or you could simply do it yourself. 

I hope this is able to solve your problem. If that is not the case it would be useful if you could send me the output.hdf5 file and the psf file that you used as well. 

Kind regards 
Dries

**Comment by drsamadi** [comment]
Hi Dries,
thanks for your fast reply.
I have looked at the rotated PSF, it is indeed correctly oriented (in the CCD2 frame) but it is a PSF without diffusion (i.e. optical PSF), therefore it is not useful since we want: 
a) to compare with the inverse PSF and  the diffused PSF. Also   we want 
b ) to compare the light-curves generated from the imagette (using the PSF fitting) with those generated using the perfect knowledge of the PSF. 
b) to compare the on-board generated light-curves corrected using the inverse PSF with those corrected with the perfect knowledge of the PSF. 

Réza

**Comment by Dries-Seynaeve** [comment]
Hello Réza

I will change the way the diffused PSF will be saved, so that it will be correctly rotated. 

Kind regards 
Dries

**Comment by Dries-Seynaeve** [comment]
Hi Réza

This is implemented with the latest version of the develop branch. Let me know if this fixes the issue. 

Kind regards 
Dries

**Comment by drsamadi** [comment]
Hi Dries,
I have tested the new version but I get the following error:
  what():  HDF5File::readArray(): /Coordinates map/Undistorted/x not in file.
it seams that something is missing in the  HDF5 file provided to me by Denis.

**Comment by drsamadi** [comment]
I have tried to download some of the HDF5 provided in this website:
https://ivs-kuleuven.github.io/PlatoSim3/_reqs_run.html
however the ftp server ask me a login and password, which I do not have.

**Comment by drsamadi** [comment]
thanks for the password. I have downloaded one of the HDF5 file (PSF_Focus_0mu.hdf5) . I have tested this PSF file with my simulation however because the field distortion is now controlled via the MappedFromFile PSF, the star I'm simulating is not longer found in  my sub-field. 
In order to infer the RA DEC of my star, I'm usually using referencefFrame.py   however I think this routine cannot deal with the information about the distortion stored in the HDF5 file.
How do you proceed in that case to correctly setup the inertial star position in order to get the star at the right place in the CCD?

**Comment by Dries-Seynaeve** [comment]
Hello Réza

Thanks for bringing this to our attention, we need to implement some extra code to be able to deal with this mapped distortion. I will look into this. 

Kind regards 
Dries
