### ISSUE TITLE
KDA introduce slight inter-pixel offset to star positions  

### ISSUE THREAD

**Issue by nicholasjannsen** [IvS-KULeuven/PlatoSim3#672]
## Problem outline:

I have noticed that there is a slight inter-pixel shift of the Center-Of-Brightness (COB) of the target star within my imagettes simulations for when the Kinematic Differential Aberration (KDA) is `on` and `off`, respectively. This shift of about 0.1 pixel is not recorded by the stellar coordinates, however you choose to include the KDA or not. 

## PlatoSim settings:

The simulations was performed with the N-Cams and with jitter and TED turned off. 
PlatoSim version: 3.5.1.

## How it was discovered? 

The inter-pixel shift was discovered using the PSF inversion module of the L1 pipeline, which systematically returns a inter-pixel shift of the stellar coordinates of around 0.1 pixel when the KDA is on compared to when KDA is off. When the KDA is turned off the coordinates returned from this module matches within the uncertainties to the output star coordinates of PlatoSim.

**Comment by denisGrBach** [comment]
Hi, this is expected behavior. KDA basically is stellar aberration corrected by the LoS aberration. Thus, all stars, except a star on the LoS will follow some kind of ellipse over a year. The attached figure shows the displacement of about 80 stars in the course of one year. For more details see the FGS performance report, PLATO-DLR-PL-RP-0003.

[kdaXY.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/7989138/kdaXY.pdf)

**Comment by drsamadi** [comment]
Hi Denis
there is a misunderstood here . It is clear that the DKA changes the position of the star and that this position is going to change during the observations. However, the problem is that we need to know exactly where the star is at any time and in particular at the beginning of the time series.
The PSF inversion module builds a PSF by centring it at the position the star is at the beginning of the micro-scanning ; this position is inferred from the information given in rowPix and in colPix (StarPostions dataset).
Furthermore the inversion module takes into account the displacement of the star during the microscanning according to the information given in  rowPix(t) and in colPix(t) .
We have build two simulations, one with DKA on and the other with DKA off.
In both cases we have the same initial position:  (rowPix(t=0), colPix (t=0)) are the same.
However, the PSF obtained with DKA on is slightly shifted and not correctly centred while the one obtained with DKA off is perfectly centred in the 6x6 pixel area  in which the inverse PSF is decomposed.
This suggests that the information given in (rowPix, colPix)  does not reflect the exact position of the star.

**Comment by denisGrBach** [comment]
ok, sorry, I misunderstood the issue than.

**Comment by nicholasjannsen** [comment]
The issue has been resolved:

The origin to the inconsistency mentioned above was due to a the usage of the initial position of the star in the `StarCatalog/rowPix` and  `StarCatalog/colPix` which is not exactly the same as the one given in `StarPositions/Exposure00000/colPix` and `StarPositions/Exposure00000/rowPix`. What happens is that `StarCatalog` is created once in the simulation, and it takes the stars that are selected and takes the RA and Dec positions from the inputfile. It then uses these values to create the col/row positions of that star. The problem is that it does this only once and doesn't take aberration into account (only distortion).
