### ISSUE TITLE
Partial readout 

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#675]
Hi,
I've tried the partial readout mode for a Normal camera but don't understand what I get.
My setup for the partial readout is the following:

       Partial:
          FirstRowReadout:           4000               # First row that will be read out by the FEE in partial-readout mode
          NumRowsReadout:            1000            # Number of rows that will be read out by the FEE, in partial-readout mode

For the subfield:
    ZeroPointRow:                    0               # Row of the (0,0) pixel of the subfield [pixels]
    ZeroPointColumn:                 0               # Column of the (0,0) pixel of the subfield [pixels]
    NumColumns:                      2555             # Number of columns, should be >= 8 [pixels]
    NumRows:                         800         # Number of rows,    should be >= 8 [pixels]
    NumBiasPrescanRows:              30               # Nr of rows of the prescan strip to determine the bias [pixels]
    NumBiasPrescanColumns:           25              # Nr of columns of the prescan strip to determine the bias [pixels]
    NumSmearingOverscanRows:         30               # Nr of rows of the overscan strip to determine the smearing [pixels]
    SubPixels:                       128               # (Sqrt of) nr of subpixels per CCD pixel. Should be 2^n <= 128.

As output in the data set "Images" I get an image of 800 (row) x 2255 (columns). This is consistent with the definition of the subfield however I'm supposed to have readout  1000 rows due to partial readout mode ? Where is this 1000x 2255 image stored ? 
It is obviously not in the 'SmearingMaps' since the latter has a size of 30x2555.

Furthermore, I had a visual inspection on the  800 (row) x 2255 (columns) image. The latter show a structured stellar field, however since my readout start at row = 4000, the row 4000 to 4510 should indeed correspond to physical pixels and thus show the image of the stars in the FoV. However, row 4510 to 5000-4510= 4490 correspond to virtual pixels (parallel over-scan pixels) and therefore should only show a smearing pattern no ?

Did I miss something?

Réza

PS: PlatoSim 3.5.2-8-g79e66d1f

**Comment by Dries-Seynaeve** [comment]
Hello Réza

The way PlatoSim deal with Partial Readout is very basic. It only is used to calculate the readoutTime before the next exposure and the readoutTime during the next exposure (which is 0 for N-Cams). PlatoSim simulates the entire subfield that is specified by the user, independent of the readout mode so in a way it is up to the user to specify a subfield in the part of the CCD that is read out.

The subfield that you have selected would fall on the part of the CCD that would be dumped, but as mentioned before PlatoSim doesn't take this into account and still simulates these stars. So I think in order to have something that would be representative you should select a subfield that has rows > 4000.

In your case, 450 physical rows are read out and 550 "virtual" rows are then read out which should consist of a smearing map. PlatoSim currently is not able to simulate these virtual rows correctly, it would be possible to simulate a subfield from rows [4000,4510] to show the correct physical rows. The 550 virtual rows should be simulated using a smearing map, but PlatoSim as it currently is, would not use the correct exposure time for these rows. I will add this item to my TODO list.

I hope this explains a bit how PlatoSim currently deals with Partial Readout.
Kind regards
Dries

**Comment by drsamadi** [comment]
Hi Dries,
ok for this clarification.

In principle the partial readout is implemented for PLATO CCD in order to acquire a large number (~300) of parallel over-scan rows because with the nominal readout scheme it is not possible to read more 50 parallel over-scan rows.
However, in addition with the 300  parallel over-scan rows, it will be probably required to acquire a couple of physical rows at the top of the CCD.
The number of  physical rows requires is not yet specified, but this could be  something like 300 rows (because the traps with the slowest release time constant release charges up to a distance of about 150 pixels -- if the rows are transferred at the same speed than in the  nominal readout scheme, see PLATO-LESIA-PDC-TN-0030 -- it should be however noticed that the release time constant  strongly depends on the CCD temperature, thus the number of physical and virtual rows to be acquired will need to be adapted to the CCD temperature). 

This means that the first 4510-300 = 4210 rows dumped and then in total we read 300+300=600 rows.
The first 300 corresponds to physical rows and if I understand will be stored by platosim in the  Image data set provided that the subfield parameters are correctly set.
On the other hand the 300 remains rows will be virtual rows and will be stored by platosim  in the SmearingMaps data set.
Right?

Réza

**Comment by Dries-Seynaeve** [comment]
Yes, I believe this is how it should be simulated.
