### ISSUE TITLE
How to set target attitude?

### ISSUE THREAD

**Issue by PLATO-OS** [IvS-KULeuven/PlatoSim3#703]
We assume that the target attitude is calculated using the RA and DEC parameters of the observing parameters section from the yaml file. Is there a possibility to set the roll angle directly?

We need to be able to define the full attitude (RA, DEC and roll angle) that is being simulated and not only the direction (RA and DEC only) in which we point.

**Comment by JorisDeRidder** [comment]
I'ld like to make sure what your actually want: to specify the angle around the optical axis of the telescope, or the angle around the pointing axis of the platform?

**Comment by PLATO-OS** [comment]
We refer to the angle around the pointing axis of the platform.

**Comment by JorisDeRidder** [comment]
That would be the parameter `Platform::SolarPanelOrientation` in the yaml inputfile. Although the comment says that you can choose between 0, 90, 180, and 270 degrees to keep the solar panels pointed towards the Sun, you can in fact choose any angle.

**Comment by denisGrBach** [comment]
I reckon this is additional to the already calculated roll angle due to the sun direction, right? If so, can the roll angle also be set freely?

**Comment by JorisDeRidder** [comment]
How would you define the zero-point of the roll angle?

**Comment by denisGrBach** [comment]
If I remember right, the current implementation constructs the attitude rotation matric from the LoS vector and the sun direction. Equivalently this could also be done by consecutive rotations Rz*Ry*Rz. Maybe the following figure is helpful.

[frames.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/8831865/frames.pdf)

**Comment by JorisDeRidder** [comment]
How exactly is this different from the current PlatoSim implementation? In PlatoSim the SolarPanelOrientation's zero point is also calculated from the meridian going through the platform pointing vector and the Sun's pointing vector.

**Comment by denisGrBach** [comment]
As far as I see the SolarPanelOrientation's zero point (kappa?) is not zero, e.g. when using the SPF (ra=86.7987, dec=-46.3959).

**Comment by jcabrera271828** [comment]
Dear @JorisDeRidder ,

As discussed today in the Performance meeting, the statement is correct:  
<<In PlatoSim the SolarPanelOrientation's zero point is also calculated from the meridian going through the platform pointing vector and the Sun's pointing vector.>>

However, the Prime calculates the SolarPanelOrientation being 0 when the Sun is at its maximum elevation in the PLM reference frame. The particularities are described in the document PLATO-DLR-MIS-HO-0006
[PLATO-DLR-MIS-HO-0006_v3.0_clarification_on_quaternions.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/9617678/PLATO-DLR-MIS-HO-0006_v3.0_clarification_on_quaternions.pdf)

Note also that the Prime calculates the rotation to be 0 degrees *in the ecliptic reference frame*, not in the equatorial reference frame!

We should review the definition in PLATOSim to make it compatible with the Prime constraints and make some tests (for example, where PPT provides pointing direction and rotations and the expected coordinates of the X,Y,Z PLM axes).

**Comment by JorisDeRidder** [comment]
Hi Juan,

Thanks for the attached PDF document. It would require quite a number of modifications to PlatoSim and its documentation to implement this. Just to be sure that the time investment is worth it: can you give a concrete example of needed simulations where the exact rotation of the FOV really matters?

**Comment by jcabrera271828** [comment]
Hi @JorisDeRidder ,

the most urgent topic is the FGS (@denisGrBach). Currently, the FGS is becoming quaternions from the Prime, but cannot reproduce the pointing with PLATOSim because of the different assumptions on the rotation. The FGS performance shall not depend on the rotation, but the configuration has to be consistent with the Prime orientation in space because of the close loop.

As a workaround (and I think it is possible to do this with PLATOSim, but correct me if wrong) we can configure a rotation in PLATOSim that reproduces the expected behaviour by the Prime. We would need to be able to reproduce the following:
- Prime provides quaterion
- We are able to orientate the 3 axis of the Payload Module (PLM) reference frame as follows (I am providing equatorial coordinates):

 We start from a quaternion in *Prime* notation:
 (0.000125691   0.055627652  -0.915161687  -0.399230056)

 We convert the quaternion to *PMC* notation:
[        s,        vx,        vy,        vz]     norm( q)
[ 0.000126, -0.055628,  0.915162,  0.399230] 1.000000e+00

 We obtain the pointing direction in equatorial coordinates:
 93.49645458987511 deg; declination: -42.939889143751394 deg
 where we verify that this is LOPS1 (see Nascimbeni et al. 2022)
 or close enough; here we might have an issue with BCRS vs GCRS
 that we have to confirm with the Prime.

 We want however the pointing of the X, Y, Z axes of the PLM:
 185.85531 deg; declination:  -2.53252 deg [-0.9938111  -0.10191695 -0.04418641]
  98.56894 deg; declination:  46.94797 deg [-0.10171623  0.67504186  0.73073408]
  93.49645 deg; declination: -42.93989 deg [-0.04464652  0.73070611 -0.6812307 ]

I can provide python scripts to do this (but we should double-check with Sami before we made this available)

**Comment by JorisDeRidder** [comment]
> If I remember right, the current implementation constructs the attitude rotation matric from the LoS vector and the sun direction. Equivalently this could also be done by consecutive rotations Rz_Ry_Rz. Maybe the following figure is helpful.
> 
> [frames.pdf](https://github.com/IvS-KULeuven/PlatoSim3/files/8831865/frames.pdf)

@denisGrBach The drawing you provided does not show the Sun to make the clarification. What are the eta and the ksi directions referring to? I guess one of them is pointing towards the Sun shield?

**Comment by jcabrera271828** [comment]
Hi @JorisDeRidder  in the frames.pdf from Denis the Z axis points to the equatorial north pole while the X and Y axes have the usual definition in the equatorial reference frame. The Sun is not shown in the picture. Depending on the right ascension of the Sun, the angle Kapa (in @denisGrBach figure, Kapa_equatorial) is chosen in such way that the solar panels point to the Sun *AND* at the time where the Sun has maximum elevation in the Payload Module Reference Frame, its azimuth in the Payload Module Reference Frame is zero. The Prime fixes Kapa_ecliptic, not Kapa_equatorial, as dsescribed in PLATO-DLR-MIS-HO-0006.
\eta and \psi describe the axes of the Payload Reference Frame before applying Kapa_equatorial.

**Comment by JorisDeRidder** [comment]
@jcabrera271828 I guess that PlatoSim should follow the Prime and work in the geocentric ecliptic reference frame to fix kappa. It's not quite clear to me what is meant by "at the time where the Sun has maximum elevation in the PM reference frame". Because of Plato's orbit the ecliptic coordinates of the Sun are constantly changing. So the Prime computes the point of maximum elevation within one observation quarter?

**Comment by jcabrera271828** [comment]
@JorisDeRidder From PPT point of view, the important facts are:

1) the Science Working Team will publish the pointing coordinates in equatorial reference frame (or any other appropriate reference frame, but most likely equatorial). See Nascimbeni et al. 2022.

2) the Science Working Team will publish the rotation of the PLM around Z_PLM as \kappa_equatorial (or any other appropriate angle, but most likely \kappa_equatorial). This is *not* in Nascimbeni et al. 2022 because at that time we didn't have the constraints from the Prime (it is reported in the paper). \kappa_equatorial is a different angle as \kappa_ecliptic (see point 4 below).

3) with this information, the PPT will compute a quaternion that will be given to the Prime. Our interface to the Prime are quaternions. See PLATO-DLR-MIS-HO-0006. Note the different conventions in the definition of quaternions (the quaternions in the Prime convention are conjugates of the PMC convention) 

4) we will verify that the quaternion is compatible with observational constraints. This includes checking that the \kappa_ecliptic value is within the allowed range. Note that \kappa_ecliptic is not the same angle as \kappa_equatorial, but there is a unique correspondence between the two (for a given pointing direction). This is as per PLATO-DLR-MIS-HO-0006.

5) the (preliminary) range of valid \kappa_ecliptic angles has been provided by the Prime. We need to consolidate these values (and understand the margin philosophy), but the most safe assumption is to fix \kappa_ecliptic = 0 + n*90 degrees; with n=0,1,2,3. The value of n is determined by the time of the start of the observations and it is chosen such that when the Sun has maximum elevation in the PLM reference frame, the azimuth of the Sun in the PLM reference frame is zero. 

So yes, the Prime computes the point of maximum elevation within one observation quarter and makes sure that the \kappa_ecliptic chosen is such that the Sun exclusion angle requirements are verified. If Sun exclusion angle requirements are not verified, it is time to change \kappa_ecliptic by 90 degrees.

Having said that, the choice of PLATOSim (to work in geocentric ecliptic reference frame vs equatorial reference frame) is up to PLATOSim, as long as we can interface with the Science Working Team choices. Note that the Prime has not explicitly said whether they use the geocentric ecliptic reference frame or the barycentric true ecliptic reference frame (or any other convention) For the purpose of the alignment of the solar panels to the Sun it doesn't play a role (i.e. the error of using one or another is probably within the margin philosophy, margin philosophy that has not been shared with the PMC). 

Perhaps we should organize a telecon and make sure that we provide you the information you need.

Currently, the Sun exclusion angle requirements have been provided to us as a semi-analytical form (probably an analytical best approximation to a numerical study, with some margins that have not been communicated to the PMC).

**Comment by PLATO-OS** [comment]
@JorisDeRidder what do you think when the feature will be implemented? We heavily rely on this update for the image generator and FGS testing activities on the spacecraft at Prime. We should get our software ready by the end of this month which needs to include this feature of PlatoSim.

**Comment by JorisDeRidder** [comment]
I wasn't aware of your schedule at Prime, I thought the new feature was needed by early spring, not end of January. I have to admit that the end of this month will be really difficult because of other commitments.

**Comment by PLATO-OS** [comment]
I'm sorry, I thought it had been communicated that we have an urgent need for this feature. What would be your current best estimate when the feature could be implemented? As far as I've understood, there is already a plan for the implementation (which was discussed sometime in December) and it just needs to be implemented and tested.

**Comment by PLATO-OS** [comment]
Issue solved
