### ISSUE TITLE
Discontinuous background

### ISSUE THREAD

**Issue by drsamadi** [IvS-KULeuven/PlatoSim3#711]
Hi,
I was trying to generate a full image with a flat background (no stars), and I see that the intensity in the image shows some discontinuities . The following plot shows a cut around a given column of the CCD:

![Screenshot from 2022-08-25 16-53-29](https://user-images.githubusercontent.com/19569211/186698994-1d55e3fa-6fe6-4fe2-a640-0360b4b46c40.png)

I attache my configuration file.
[02.yaml.TXT](https://github.com/IvS-KULeuven/PlatoSim3/files/9425844/02.yaml.TXT)

Did I made something wrong in my setup ?

Platosim version: 3.5.3-47-g27cbaa3e

**Comment by Dries-Seynaeve** [comment]
Hi Reza

I believe this is due to the relative transitivity. This effect also included vignetting and it is this effect that you see. If you switch this off in `CCD/IncludeRelativeTransmissivity` you should see a constant background. 

Kind regards 
Dries

**Comment by drsamadi** [comment]
Hi Dries,
ok I see however it is obviously physically not acceptable to have such large discontinuities in the vignetting no ?
If I understand correctly such discontinuities should also affect the star image no ?
Réza

**Comment by Dries-Seynaeve** [comment]
When I plot a similar image, my discontinuities are only 1, which is because PlatoSim rounds to the nearest int for [ADU]. So this is to be expected. 

The image I obtain is very similar in shape to the one you have produced though The y values do not seem to match however. Can you share how you obtain your image, maybe there is something wrong with a python routine that you use. 
![discontinuity](https://user-images.githubusercontent.com/74176898/186718682-abeba14e-dddb-449d-9728-4cce2916a8eb.png)

**Comment by drsamadi** [comment]
Hi Dries,
OK I see, these discontinuities are simply due to the quantification (25e-/ADU in my simulation).
In the plot, the intensity is plotted in e-, hence the steps we see are exactly equal to 25e-.
So there is no issue here. Sorry for the trouble. I will close it. 
Réza
