### ISSUE TITLE
Allow automatic background for each pixel

### ISSUE THREAD

**Issue by nicholasjannsen** [IvS-KULeuven/PlatoSim3#729]
This is just a small reminder about the issue of the current implementation of the sky background flux: PlatoSim do not have any means of providing an automatic estimate of the background for each pixel in a simulated subfield. Only one value is used for the entire subfield which is increasingly unrealistic as the subfield is enlarged.

**Comment by manugr788** [comment]
This is just a small reminder that we really need that the option SkyBackground:  -1 works correctly

When simulating a large image (in particular a full image), we need to account for the fact  that the sky-background varies across the field of view (mostly because the presence of the zodiacal light).
In order to test our model, we need that PlatoSim simulates a coherent background model all over the PLATO instrument field of view, i.e. if we use a yaml config file simulating a subfield on telescope GroupID 1 on CCD 2 and another yaml config file where we only change the GroupID to F-CAM and CCD 3, PlatoSim should use a coherent background model over the field of view that our algorithm should have to inferred. 
The lack of this feature prevents us to test in realistic conditions the 'background window placement algorithm' and the 'background modelling' which are our main developments currently.

**Comment by Dries-Seynaeve** [comment]
Hi, this feature is now included in the Develop branch. 

To use this, in the inputfile you should set the value of `Sky/SkyBackground/UseConstantSkyBackground` to `no`. If you want to inspect the background map, you can make sure the value of `ControlHDF5Content/WriteVariableBackgroundMap` is `yes`, that way the map is saved in the output HDF5 file. 

Just as a small note on this feature:
Because calculating this map is quite intensive, we only calculate the map only once, at the beginning of the simulation and use this map for every time step in the simulation. We expect that this approximation is warranted for most simulations, since the data points of the sky catalog that we use, are quite spaciously distributed compared to the variations we expect.

**Comment by nicholasjannsen** [comment]
Hi @Dries-Seynaeve , very nice with this new feature! I have a few comment to the implementation from the users point of view (and potential a bug):
- Regarding your statement above: I agree that excluding the time dependence for the sky background calculation is justified as long as the user know that the stray light from celestial bodies (mainly the Moon and the Earth) are not included in this model (I'll make that very clear in the updated documentation). If a stray light model should be included in the future, the above assumption needs to be revised.  
- I would change the name of `writeVariableBackgroundMap` to just `writeBackgroundMap`. Being an astronomer I immediately relate this to a variable source.  This also relates to the next point:
- It is confusing that  both a `Background` and `BackgroundMap` entry are saved to the HDF5 file. I think the best behavior is to save a single entry called `BackgroundMap` .  In order words, we should remove the `Background` entry all together. Then if the user sets the sky background to be a constant pixel value across the subfield, the `BackgroundMap` should not be a single value, but an array of equal size as the subfield times this constant value.  I understand that this feature will take up more space (and add a bit more computation time), but I think it is worth it, in order to make the output cleaner and easier interpretative for the user. I suspect that creating and saving a single constant array in C++ would not add too much computation time even for a full-frame image(?).
- When you fetch the `BackgroundMap` in python it is stored in a "double layered array" (i.e. the array is inside an array) which is not consistent with all other image products saved to the HDF5 file.
- I'm not sure that the interpolation is performed correctly.  I have made a validation Jupyter notebook that generates an all-sky image using simulated grid points (see `/docs/technicalnotes/PlatoSim3Paper/SkyBackground.ipynb`). The output shows several features: 
  1.  There are still data gaps both in the Zodical and Galactic maps. The ecliptic poles and the equatorial poles do not seem to have been interpolated at all. 
  2. The interpolation of the data gap of the ecliptic center (i.e. the Sun's position) is not interpolated correctly.
  3. There seem to be a lower sky background flux exactly where the equatorial plane is (this is a very thin strip of background).
  4. I can't rule out a potential bug in my setup of the simulation, but I get sky background outliers equidistantly spaced (in the equatorial grid) over the all-sky projection. Also the new interpolation seem to create ring like structures for data around the equatorial poles.
  5. The previous large data gap in the Galactic map (centered at  `(lon, lat) = (130, 0) deg` in ecliptic coordinates seems to be interpolated correctly. 

Note that the validation test fails after the Background branch has been merged (i.e. simfile.run end with error code -11). I took a little while to understand why, but the new background functionality is not compatible with the function `switchOffAllEffects()` for `validation.py`. Btw I have copied this function to `simulation.py` now (and included some missing settings) which is now called `sim.turnOffAllEffects()` and `sim.turnOnAllEffects()`.

**Comment by manugr788** [comment]
Hi,
Trying to run this new version of Platosim (Develop branch) with:
```
SkyBackground:
      UseConstantSkyBackground:      no              
      BackgroundValue:               -1
ControlHDF5Content/WriteVariableBackgroundMap yes
```

I got as before, a lot of warning like this one, seems to indicate that something went wrong with the background model computation :
WARNING Sky::zodiacalFlux(): No data for (alpha, delta) = (67.901639, -68.633546)
WARNING Sky::zodiacalFlux(): No data for (alpha, delta) = (69.145284, -59.708685)`

My inputfile.

[010000001.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/11000410/010000001.txt)

PlatoSim 3.5.4-385-ge8b1e926

BTW, it seems that inputfileFast.yaml has not been updated for SkyBackground section, 
do you know what is the value for ThroughputBandwidth for F-CAM ?
In inputfile:
ThroughputBandwidth:             532             # FWHM [nm]. Is different for fast cams than for normal cams.

**Comment by Dries-Seynaeve** [comment]
Hi Manu, I suspect from the warning that you might have forgotten to build the new platosim version. Can you try to go to the build directory in platosim and run `make -j 4` in a terminal. Normally this should build the new version and these warnings should not be there anymore.

Thanks, for mentioning the inputfileFast, I will make sure this is updated. I don't know the value of the throughputbandwith, but I will ask around for this.

**Comment by manugr788** [comment]
Hi @Dries-Seynaeve ,
Usually I only do ./install.sh, 
do I have to update Platosim using ./install.sh then make -j 4 ?
I try make -j 4 but got the same results, a lot of WARNING Sky::zodiacalFlux(): No data for (alpha, delta) = (67.754852, -66.203099)

Is my version of platosim right (PlatoSim 3.5.4-385-ge8b1e926) ?

**Comment by Dries-Seynaeve** [comment]
Your version is correct, I just pushed some more changes to the develop branch that maybe fixed the issue. Can you try to update platosim and run it again. If this didn't solve it, can you share send the input file that you used, and I'll try to see what where this comes from.

**Comment by manugr788** [comment]
No changes for me, new version PlatoSim 3.5.4-391-g3a9a8c15
2023-03-17 15:01:56 WARNING Sky::zodiacalFlux(): No data for (alpha, delta) = (94.450818, -64.028274)
My inputfile is in a  [previous message](https://github.com/IvS-KULeuven/PlatoSim3/issues/729#issuecomment-1473643557)

**Comment by Dries-Seynaeve** [comment]
Hi, I believe the issue was caused by missing points in sky background map that we used. I have interpolated these gaps and believe this should work now with the most recent version of PlatoSim.

**Comment by manugr788** [comment]
Hi Dries,
There is no longer Warnings with this new release, nevertheless I am a little confused with the background Map for one camera. I simulated 4 full CCD images with only the CCD/Position parameter changing from 1 to 4.

I rotated the CCD using the script below. Is the BackgroundMap in CCD reference frame (not FP reference frame) ?

Is there any reason to explain why the 4 CCDs full images seem not to be coherent through a full camera ? This is an issue for us since we need to simulate the background over one camera.

```
import matplotlib.pyplot as plt
import h5py
from scipy import ndimage

f1 = h5py.File("010000001.hdf5","r")
f2 = h5py.File("010000002.hdf5","r")
f3 = h5py.File("010000003.hdf5","r")
f4 = h5py.File("010000004.hdf5","r")

ccd1 = f1["BackgroundMap/backgroundMap"]
rotated_ccd1 = ndimage.rotate(ccd1, -180)
ccd2 = f2["BackgroundMap/backgroundMap"]
rotated_ccd2 = ndimage.rotate(ccd2, -270)
ccd3 = f3["BackgroundMap/backgroundMap"]
ccd4 = f4["BackgroundMap/backgroundMap"]
rotated_ccd4 = ndimage.rotate(ccd4, -90)

fig, axs = plt.subplots(2, 2, sharex=True, sharey=True)
axs[0, 0].imshow(rotated_ccd1, vmin=1000, vmax=7000, origin='lower')
axs[1, 0].imshow(rotated_ccd2, vmin=1000, vmax=7000, origin='lower')
axs[1, 1].imshow(ccd3, vmin=1000, vmax=7000, origin='lower')
axs[0, 1].imshow(rotated_ccd4, vmin=1000, vmax=7000, origin='lower')

plt.show()
```

![bkg_camera](https://user-images.githubusercontent.com/12544881/226629458-dd500542-74fa-43c6-a797-53a0ba2aa3f9.PNG)

**Comment by Dries-Seynaeve** [comment]
Yes, this does seem strange. Do you have the log files  of these simulations by any chance?

**Comment by manugr788** [comment]
Yes, you can find all the simulations files here:

[https://zendto.obspm.fr/pickup?claimID=ZzcwMhGWojCehG8K&claimPasscode=vCV8FsZ9TWVFtXq8](https://zendto.obspm.fr/pickup?claimID=ZzcwMhGWojCehG8K&claimPasscode=vCV8FsZ9TWVFtXq8)

**Comment by Dries-Seynaeve** [comment]
Hi, the error is in the input file. For the simulation for CCD 4, you set the Telescope group to 4 and CCD Position to 1 instead of the other way around. I am running that simulation again to make sure the background images fit.

**Comment by manugr788** [comment]
Ah! you are absolutely right, I correct and re-runs the simulation again and give you the results on my side, thank you very much.

**Comment by manugr788** [comment]
Ok, everything seems perfect now ! 
![bkg_camera](https://user-images.githubusercontent.com/12544881/226682718-842b79ca-bb21-4c0e-9642-2d00c5e7eb7f.PNG)

**Comment by nicholasjannsen** [comment]
Hi @Dries-Seynaeve, I was wondering if my 2.-4. point above should be implemented before any new release?

**Comment by Dries-Seynaeve** [comment]
Hey @nicholasjannsen , I have implemented your suggestions. I small comment, I have changed the output format in the HDF5 file. The background map and background values can both be found under `BackgroundMap/skyBackground`, if we simulate a constant skybackground this will be a time series with the background values and otherwise this will be one background map with the same dimension as the subfield.

**Comment by nicholasjannsen** [comment]
Perfect thanks @Dries-Seynaeve! The interpolation all-sky looks great as well so I believe we can close this issue. @manugr788 are you happy with the output as well?

**Comment by manugr788** [comment]
Yes, perfect for me. You can close the issue.
Do the values in BackgroundMap have the same unit and value (photo/e-/s ?) as the previous version skyBackground scalar dataset ?

**Comment by nicholasjannsen** [comment]
Okay thanks @manugr788. Yes the units are still in [photons/e-/s]

**Comment by dianeberard** [comment]
Hello,

You were talking about adding the effect of Moon and Earth brightness to background but I can't find any issue about it (opened or closed). Do you still plan to do it ? 

Thanks !

**Comment by Dries-Seynaeve** [comment]
Hi,

Yes, this will be added. I am currently working on this very issue.  
There is currently no open Issue about this, but it is written down (together with other features we want to add), in our [Github Wiki](https://github.com/IvS-KULeuven/PlatoSim3/wiki/Upcoming-features-and-planning). 


Kind regards 
Dries

**Comment by dianeberard** [comment]
Hi Dries,

Thanks for your answer. When do you plan to release this feature ? 

Regards,

Diane BERARD

**Comment by Dries-Seynaeve** [comment]
Hi Diane, 

Normally this will be part of our next (major) release. In terms of time, this is a bit more difficult to predict. It is a pretty big feature so it depends on how long the development will take. 

Kind regards 
Dries
