### ISSUE TITLE
Background during readout time

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#8]
I am testing PlatoSim V3. I think I have found a bug.

Images dataset and SmearingMaps dataset don't have background acquired during readout time.

For example :
Let,
Offset = 1000 ADU
Background = 150 e/px/s
Readout time = 3s
Integration Time = 22 s
Gain = 17

Thus, 
SmearingMaps dataset mean (without any star component) must be :
1000 ADU + (150 \* 3) /  17 =  1026 ADU (PlatoSim V3 results is 1000 ADU, PlatoSim V2 was OK)

Image dataset (without any star component) must be :
1000 ADU + (150 \* 22) /  17 + (150 \* 3) /  17 +  =  1220 ADU (PlatoSim V3 results is 1120 ADU, PlatoSim V2 was OK)
I don't know why the mean value is 1120 ADU. Without readout background, it must be 1194 ADU.

BiasMap doesn't acquire any background, so PlatoSim V3 is OK.

**Comment by SaraRegibo** [comment]
Fixed in pull request #10

**Comment by SaraRegibo** [comment]
Assigning to Emmanuel for closure.

**Comment by manugr788** [comment]
I have just tried the new release. I am a lit bit confused with the results.
Using the same parameter as describe above I got 1016 ADU for Smearing map when I expected 1026 and 1134 ADU for image when I expected 1220, may I missed something ?

> > > import h5py
> > > import numpy as np
> > > f=h5py.File("psim_jit.hdf5","r")
> > > s=f["SmearingMaps/smearingMap000000"]
> > > np.mean(s)
> > > 1016.0776
> > > 
> > > i=f["Images/image000000"]
> > > np.mean(i)
> > > 1134.3192

**Comment by JorisDeRidder** [comment]
We are trying to reproduce your results. Could you please post the QE you used in the input file to convert the background [phot/pix/s] in the input yaml file to a background in [e-/pix/s]?

**Comment by manugr788** [comment]
Ok, I have just understood that SkyBackground parameter definition has been changed from PlatoSim V2, e-/pix/s to photon/pix/s !! Sorry !
Everything seems OK now for sky background over overscan rows, nevertheless for image it's seems there is no readout sky backround added ?
I use  
QuantumEfficiency: 0.680111
So SkyBackground = 150 e-/pix/s => 150/0.68 = 220 pho/pix/s
I get 

> > > f=h5py.File("psim_jit.hdf5","r")
> > > s=f["SmearingMaps/smearingMap000000"]
> > > np.mean(s)
> > > 1023.5963 ===> Perfect
> > > i=f["Images/image000000"]
> > > np.mean(i)
> > > 1196.9727 => that's the value without background during readout time

**Comment by SaraRegibo** [comment]
Emmanuel, would you mind attaching your configuration file to this issue?

**Comment by manugr788** [comment]
Find LESIA configuration enclosed.

[platosimV3_Lesia_configurationfile.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/229455/platosimV3_Lesia_configurationfile.zip)

**Comment by SaraRegibo** [comment]
It turns out that - for this configuration - vignetting causes a flux loss that is very close to the contribution of the readout background (giving you the impression that the readout background is not included).  If you disable vignetting (IncludeVignetting = no), you should get the expected mean of 1220 ADU for the image.

When disabling the open-shutter smearing (so the contribution of 150 \* 3 / 17 ADU disappears), the only contribution in the image is the background + electronic offset.  Without vignetting this is 1194 ADU (as expected), but with vignetting this is only 1175 ADU.  This flux loss of about 1.5% is what you would expect for your configuration (i.e. the sub-field zeropoint at (900,900)).  Adding the contribution of the readout background, you get to the number you found.

So, the readout background really is taken into account now, it is only unfortunate that the flux loss due to vignetting is roughly the same as the contribution of the open-shutter smearing.

**Comment by manugr788** [comment]
Ok, so that was due to vignetting effeec. I understand, very sorry Sara. 
What is strange is that PIS also includes vignetting and we don't get the same signal level. I think the problem comes from PIS.
Once more thanks very much Sara. I close this issue.
