### ISSUE TITLE
setup.sh / python installation directory

### ISSUE THREAD

**Issue by jcldc** [IvS-KULeuven/PlatoSim3#805]
for **setup.sh** program, it would be great to add an option for installation directory of the python programs instead of installing them in **$HOME/.local/bin/**. It would be useful when the project is installed on an NFS infrastructure with multiple users.

**Comment by nicholasjannsen** [comment]
Hi JC, indeed I fully agree. I'll the make the update asap.

**Comment by jcldc** [comment]
The ideal would be to have a true setup.py installation program

**Comment by nicholasjannsen** [comment]
You mean that `setup.sh` would be integrated with `install.sh` or that this script should install all python dependencies?

Regarding the above feature request, would it be sufficient to copy these scripts to the python environment. E.g. while using conda for the envionment manager, then this will be `$CONDA_PREFIX` and the scripts will be located the same place as all your python packages that either has been installed with conda or with poetry? Note that the reason why `setup.sh` do not install the python packages is because I want to separate the different types of PlatoSim installation: PlatoSim alone `poetry install`, PlatoSim+PLATOnium `poetry install --with platonium`, and PlatoSim+PLATOnium+L1pipeline `poetry --with platonium --with pipeline`.

**Comment by jcldc** [comment]
I mean to write a standard **setup.py** to install correctly the package according to the **virtual/conda environment**.
And moreover, I noticed that in **varsim** and  **picsim** there is the creation of a data directory to download data at runtime.
It would be better to specify an environment variable to specify a location, different of where are the source code, for these data.
(if you stay with setup.sh, yes it would be better to copy scripts in $CONDA_PREFIX or virtualenv prefix, but the best way is setup.py)

**Comment by nicholasjannsen** [comment]
- This could be done, but currently I think it's better to just keep it as a separate step using `poetry`. Generally such a `setup.py` script would still need to be told to install the minimal package usage or only including PLATOnium and the L1 pipeline. 
- I not sure if I understand why a download location different from `PlatoSim/python/varsim/data` is beneficial? The reason I did this is because I want to have everything contained within PlatoSim. I would argue it would be better to download this data into `PlatoSim/inputfiles` since they would be globally known already in the YAML file then. 
- I'm working on making `setup.sh` script universal to both Linux and Mac users. I didn't make `setup.py` since the point is that the user should be able to run PlatoSim from bash alone (independent of python). This script is mainly needed to make the `platosim` executable (and `platonium`, `picsim`, etc.)

**Comment by jcldc** [comment]
right now data and python files are in the same directory, in term of computing science it's not recommended. For example here in Marseille, I have installed the project in an NFS partition for all users and I had to chmod 1770 picsim and varsim in order that everybody could download their data. It would be far better that each users declare its own location to DL data different from where is located source code.
Maybe I forgot to mention that Platosim project is installed here in Marseille on a computing cluster. Then there is only one installation for all users. All data are shared through NFS

**Comment by nicholasjannsen** [comment]
So moving the files to `PlatoSim3/inputfiles/` would not be sufficient, you want them completely out of the `PlatoSim3` folder?  For me it doesn't matter much, but I want to keep the idea that the download happens completely automatically upon a first execution of either `picsim` or `varsim`. Could it be that this is a quite specific problem with the access your cluster because downloading from our cluster do not cause any problems?
