### ISSUE TITLE
Aberration validation tests take too long

### ISSUE THREAD

**Issue by JorisDeRidder** [IvS-KULeuven/PlatoSim3#860]
The validation tests are slow to execute (more than 10 minutes!), and hamper fast development and testing. Two of the main culprits are the tests on absolute and relative aberration. These should be rewritten so that they run faster.

**Comment by nicholasjannsen** [comment]
I would also suggest to print the execution time of each script after the `Success` statement. In that way we can order each of the script after their computation time (starting with the fastest scripts) and catch failure of a fast script faster (instead of waiting until e.g. the aberration script finishes). 

The stellar variability test also takes quite some time. Is it not enough to just to simulate 30 exposures for a single star and check if the flux difference is correct?

**Comment by Dries-Seynaeve** [comment]
I have been able to reduced the time it takes to run the tests from 1000s to now 380s.

I also changed the order of the tests to be more in line with what @nicholasjannsen  suggested.
