### ISSUE TITLE
ACS new datasets : dx and dy for the center of the subfield into FP frame 

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#88]
In order to correct jitter on lightcurve generated with PlatoSim output data we need to know the exact position of the subfield center for each AOCS time step.

Therefore, may you add two new datasets into ACS :
- dxFpSubfieldCenter = dx of the center of the subfield into FP coordinates [in pixels], XCenterFp - XCenterReferenceFp, for each ACS time step 
- dyFpSubfieldCenter = dy of the center of the subfield into FP coordinates [in pixels], YCenterFp - YCenterReferenceFp, for each ACS time step

Emmanuel

**Comment by JorisDeRidder** [comment]
Could you give a bit more explanation? The way PlatoSim is currently implemented, the subfield is a fixed rectangular subimage on the CCD. Therefore the subfield center is also fixed, i.e. independent of the jitter. The same holds for the location of the subfield in the focal plane: the subfield is fixed on the CCD, the CCD is fixed in the focal plane, and therefore the subfield center focal plane coordinates are fixed. The only thing that changes due to the jitter, is the piece of sky that is projected on the subfield. I.e. the (RA, Dec) coordinates of the subfield center slightly change due to the jitter. Is it the (RA, Dec) of the subfield center, you would like to see stored in the HDF5 file?

**Comment by manugr788** [comment]
> The CCD is fixed in the focal plane, and therefore the subfield center focal plane coordinates are fixed. The only thing that changes due to the jitter, is the piece of sky that is projected on the subfield. I.e. the (RA, Dec) coordinates of the subfield center slightly change due to the jitter. 

Yes, you are right.  Actually, we need to know the impact of this change due to the jitter in terms of dx, dy over the focal plan. It's like if there was a star positioned exactly at the center of the subfield, what will be its focal plane (dx,dy) for each ACS time step ? We need this information to determine the exact position of a surface correction to subtract jitter effect from signal.

See below the displacement file output generated by PIS :

 head pis_jit/pis_jit_displacement.dat
#Time[s] dXfp[pixels] dYfp[pixels] Yaw["] Pitch["] Roll["]
   0.0000000000    0.0085935735    0.0008577392   -0.1087366616    0.0022591282   -0.0925855910
   0.1250000000    0.0090534794    0.0009901695   -0.1148039119    0.0035268126   -0.0971531340
   0.2500000000    0.0096805534    0.0014496726   -0.1236901618    0.0090366157   -0.1031394500
   0.3750000000    0.0102686138    0.0019515318   -0.1323905479    0.0150694310   -0.1075473400
   0.5000000000    0.0106293373    0.0027720180   -0.1387638363    0.0257611000   -0.1103036400
   0.6250000000    0.0107356737    0.0037479318   -0.1423702269    0.0388124981   -0.1098689700

**Comment by JorisDeRidder** [comment]
Ah, now I understand what you mean. I'm not sure that there is one unique pair (dx, dy) that you can use for every star in the field. The reason is the (non-linear) optical distortion. If a star moves because of the jitter a bit away from the optical axis, then it will "feel" a slightly different distortion. Therefore a star in the subfield closer to the optical axis will be displaced with a slightly different (dx, dy) than a star in the subfield farther away from the optical axis. 

What you could do, is to work on a star-by-star basis. In the HDF5 file, the folder StarCatalog contains for every star the "unjittered" focal plane coordinates (xFPmm, yFPmm) in mm, and the unjittered CCD pixel coordinates (rowPix, colPix). In the folders StarPositions/Exposure0000??/  you can find for every star the same information, but then after jitter. Subtracting the two gives you the desired (dx, dy) for every time point, but then for every star separately.

**Comment by manugr788** [comment]
Ok, in fact I have already done this but I was wondering if it was more realistic to have this value for the center of the subfield like the information gave by PIS. I will ask to Reza and let you know his answer.

**Comment by manugr788** [comment]
I have asked to Reza. As you proposed, we will use the "unjittered" focal plane coordinates (xFPmm, yFPmm) in mm, and the unjittered CCD pixel coordinates (rowPix, colPix) do make a difference.
I close this issue.
