### ISSUE TITLE
Platonium install does not put platosim into python

### ISSUE THREAD

**Issue by guyrixon** [IvS-KULeuven/PlatoSim3#884]
After installing platosim and the python stuff needed for platonium, and activating the platosim embironment in conda:

(platosim) gtr@spartan05:~/platosim3$ platonium -h
Traceback (most recent call last):
  File "/home/gtr/anaconda3/envs/platosim/bin/platonium", line 37, in <module>
    import platosim.utilities       as ut
ModuleNotFoundError: No module named 'platosim'

(platosim) gtr@spartan05:~/platosim3$ which python
/home/gtr/anaconda3/envs/platosim/bin/python

**Comment by guyrixon** [comment]
This problem has cleared itself after logging out last night and logging in again this morning. Possibly worth putting an instruction to log out and in again in the docs?

**Comment by nicholasjannsen** [comment]
The problem lies within bash knowing the global variable `$PLATO_PROJECT_HOME`. Whenever you define a new path to bash (e.g. `export PLATO_PROJECT_HOME=/path/to/PlatoSim3/inputfiles/`) you always need to refresh your `.bashrc` in your current working directory. In Linux this is done by either `source ~/.bashrc` or `. ~/.bashrc` from your `$HOME` folder. Alternatively one can always just close the terminal and open a new terminal. When a new terminal is opened by the user the `.bashrc` is reloaded with the paths you have just exported. The script called `setup.sh` copy these imports to your `/path/to/PlatoSim/.bash_profile` file such that all python functions are known by your Conda environment and to the system. 

I'll make a note about it and include it in the docs for the future release.
