### ISSUE TITLE
Platonium installation issue - ChefBuildError

### ISSUE THREAD

**Issue by AstroSaad** [IvS-KULeuven/PlatoSim3#898]
Hello all!

I'm trying to install platonium on a new environment on my mac OS machine.

When I run the command "poetry install --with platonium", I get the error message "ChefBuildError" when it tries to install the "ligo-skymap" package.
The full message is as follows:

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  Traceback (most recent call last):
    File "/Users/saadahmed/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/saadahmed/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/saadahmed/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/var/folders/fm/rs_zmvgx13d4_d5x80knr0lm0000gn/T/tmpqmbk9pm8/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/var/folders/fm/rs_zmvgx13d4_d5x80knr0lm0000gn/T/tmpqmbk9pm8/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "/var/folders/fm/rs_zmvgx13d4_d5x80knr0lm0000gn/T/tmpqmbk9pm8/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 126, in <module>
    File "<string>", line 18, in get_extensions
  ModuleNotFoundError: No module named 'numpy'
  

  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/chef.py:152 in _prepare
      148│ 
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│ 
      151│             if error is not None:
    → 152│                 raise error from None
      153│ 
      154│             return path
      155│ 
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with ligo-skymap (0.6.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "ligo-skymap (==0.6.1)"'.

**Comment by nicholasjannsen** [comment]
Hi @AstroSaad, did you install with using the `develop` branch? I'm doing a lot of updates these days, hence, please pull the `master` branch and use that. You simply follow the instruction given on our documentation. I have tested that the `pyproject.toml` works for a Anaconda3 environment of python 3.9. In the future I hope to remove this `ligo` packages all together since it is very buggy every time I have to update other python dependencies.  

Please try that and get back to me.

**Comment by AstroSaad** [comment]
Hi Nicholas. I've swtiched over to the master branch and I'm getting the same error but for a different python package, "healpy":

  • Updating healpy (0.0.0 /Users/runner/miniforge3/conda-bld/healpy_1697027002295/work -> 1.16.5): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

**Comment by nicholasjannsen** [comment]
Hi @AstroSaad, it could potentially be a Mac issue because I just fetched the master branch and installed all python packages successfully with poetry on my linux machine. Mind that the PlatoSim installation and the python packages needed to run PLATOnium are completely decoupled. With that in mind, try to follow exactly these steps that I did:

```
cd
git clone https://github.com/IvS-KULeuven/PlatoSim3.git
conda deactivate
conda create -n platonium python=3.9
conda activate platonium
cd PlatoSim3
poetry install --with platonium
```

Do you do anything different from that (maybe except from the fact that I install PlatoSim in the `$HOME` directory)? I use Poetry version 1.5.1, so if the above fails, try with this version. Potentially, try to reinstall poetry if it still doesn't work.  

Perhaps you have a buggy conda installation because I have never seen the error `ChefBuildError` before. Also, since I see that poetry tries to **update** a package, it points in the direction that you are potentially messing up several installing attempts with poetry. Start from a clean slave as above and let me know how it goes. 

Note that when you clone the master branch there is no `poetry.lock` inside the `PlatoSim3/` folder. However, after you run poetry for the first time, then description of the `pyproject.toml` file will generate this file such that you have a "frozen" version that works with the chosen version of python (i.e. Python 3.9 in this case).  I would consider

I'll also show these commands tomorrow in the PLATOnium tutorial. Note I'm not gonna show how to install `platosim` itself since we have a very elaborate documentation on this.

**Comment by AstroSaad** [comment]
Hi Nicholas. I believe this issue I've been facing is a Mac issue.

I cleared the PlatoSim files and re-installed and downloaded everything like your steps. I uninstalled and re-installed poetry. However, none of those solutions worked and I still get the same error. It comes with an additional message:

"Note: This error originates from the build backend, and is likely not a problem with poetry but with healpy (1.16.5) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "healpy (==1.16.5)"'."

I've looked into the documentation for healpy where it was said that other Mac users have had issues installing through pip. I believe poetry uses pip installations so this might be where the issue is coming. I can use conda to install healpy but poetry doesn't recognise that.

I feel like it might be more worthwhile to switch to using linux on a virtual machine.

**Comment by nicholasjannsen** [comment]
Thanks for the update Saad, and good you solved it! Sorry to hear you went all that way to find that is it a Mac issue, but indeed I would recommend to use a Linux (virtual) machine for small testing purposes of PLATOnium. If you have a cluster to work on, then you might go straight ahead using that instead. I'm closing this issue, but feel free to open more issues as you progress.
