### ISSUE TITLE
Platonium and varsim errors

### ISSUE THREAD

**Issue by AstroSaad** [IvS-KULeuven/PlatoSim3#899]
Hello all,

I've got an installation of platonium on one of my environments on my mac OS system. I'm able to run "picsim" without too much trouble. However, I get errors when I try to run either varsim or platonium.

When I try to run varsim, I get the error "ModuleNotFoundError: No module named platosim.phoenix".

I'm assuming my platonium error is probably related. When I try to run platonium, I get the error "Not valid PLATO field!Options: NPF, SFP, LOPN, LOPS2"

**Comment by nicholasjannsen** [comment]
Hi again @AstroSaad, indeed you can't run `varsim` or `platonium` if you cannot install all python packages using poetry (or conda for that matter). Make sure that both the PlatoSim installation (i.e. the c++ installation) is successfully installed and then make sure that the poetry installation is successful. I'm closing this issue since it's due to your previous installation problem #898. 

Btw I'll expand the documentation for PLATOnium very soon. The reason why you get that error message is because you need to replace the `starcatalog.txt` in your YAML file with a string being either `NPF`, `SPF`, `LOPN`, or `LOPS2`. This made to automatically setup the platform for the pointing of one of the planned PLATO pointing fields. I'll document that better. Also if you create a stellar catalogue using `picsim`, then a YAML file will automatically be cloned to your `PLATO_WORKDIR/<project_name>/input` folder if it doesn't exist.

**Comment by nicholasjannsen** [comment]
As mentioned before PLATOnium is very experimental in the `develop` branch for now. Please use the `master` branch.
