### ISSUE TITLE
Add 6 datasets to StarXCatalog HDF5 Group 

### ISSUE THREAD

**Issue by manugr788** [IvS-KULeuven/PlatoSim3#9]
In order to be able to use DPA-WG ligtcurve pipeline with PlatoSim V3 inputs, DPA-WG needs :
- Add 6 datasets to StarXCatalog HDF5 Group  :

X  => in pixel within the imagette, X = Xccd - X0imagette

Y   => in pixel within the imagette, X = Xccd - X0imagette

Xccd  => in pixel figured out using focalPlaneToPixelCoordinates()

Yccd  => in pixel figured out using focalPlaneToPixelCoordinates()

Xfp   => in mm figured out using gnomonicProjectionSkyToFocalPlane()

Yfp   => in mm figured out using gnomonicProjectionSkyToFocalPlane()

**Comment by JorisDeRidder** [comment]
Is part of what you need already available in the group StarPositions?
For example, StarPositions/Exposure000000 contains the pixel and focal plane coordinates of each star.
Note that each exposure has a different star list, because some stars may jitter/drift out of the FOV.

**Comment by manugr788** [comment]
Yes, but the first exposure must already undergo jitter coming from jitter file, and we need all this data for a no-jitter exposure. Actually, we need the raw StarPosition data.That's why I ask for have it within starCatalog Group.

**Comment by JorisDeRidder** [comment]
Now I understand better. We'll do our best to implement it. Meanwhile, as a quick-and-dirty intermediate solution, you can put the yaw/pitch/roll to 0.0 during the first 22 seconds in the jitter file. This will make the arrays in StarPositions/Exposure000000 exactly what you want.

**Comment by rhuygen** [comment]
The StarCatalog group of the HDF5 output file now contains the following arrays:
- starIds
- RA [rad]
- Dec [rad]
- Vmag
- xFPmm [mm]
- yFPmm [mm]
- colPix
- rowPix

The stars in the StarCatalog are those that were detected on the subField during one of the exposures. Not all stars might be detected in all exposures due to Jitter.

The star positions [xFPmm, yFPmm[ and [colPix, rowPix[ are the initial positions of the stars before any Jitter or thermo drift was taken into account. They include however field distortion if this was requested by the user.
