### ISSUE TITLE
Platonium Pandas incompatibility

### ISSUE THREAD

**Issue by AstroSaad** [IvS-KULeuven/PlatoSim3#908]
Hello all. I've noted an issue to be aware of.

I've installed platosim with platonium on a linux system with all the dependencies. I'm on the master branch.

When I run the "picsim" part of platonium, I get an error when fetching contaminants: "AttributeError: 'DataFrame' object has no attribute 'append' "

To get around this issue, I've downgraded my pandas installation to 1.4.1. This is something that should be updated in the code as the newer releases of pandas don't have the "append" function. The new function is "concat" I believe.

**Comment by nicholasjannsen** [comment]
Hi Saad, 

thanks for this, and indeed that's a bug. I have already corrected this in the new release soon to come.

Cheers
Nicholas

**Comment by AstroSaad** [comment]
On a related point, there's an issue with with numpy as well. Running picsim gives a warning: "UserWarning: A NumPy version >=1.18.5 and <1.26.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

I've downgraded to numpy 1.23 to work forward

**Comment by nicholasjannsen** [comment]
Hi Saad, which Python version are you using? I checked Python 3.8 and 3.9 (which are the recommended versions for now) and there is no warning from those.

**Comment by AstroSaad** [comment]
I'm on Python 3.9 so I'm unsure why the warning comes up

**Comment by nicholasjannsen** [comment]
Hi again. I overlooked that you are using the `master` branch for PLATOnium - you should use the `develop` branch for PLATOnium. A stable version of PLATOnium will be part of the master branch in the coming release. As mentioned above, the develop branch is well tested for the usage of this toolkit. Mind that you also need to use the same version of PlatoSim as mentioned in the video tutorial I made. The current version of the develop branch has a lot of changes which many new functionalities.

**Comment by AstroSaad** [comment]
Hi Nicholas.

I was away for a bit but I'm back now. I switched to the develop branch but I get a new error when I run picsim:
"Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/picsim", line 57, in <module>
    import platosim.picsim.starquery as starQuery
ModuleNotFoundError: No module named 'platosim.picsim.starquery'
"
Would you be able to let me know what to do?

**Comment by nicholasjannsen** [comment]
I think you are using a old version of the develop branch no? We don't use the import `platosim.picsim.starquery` anymore but instead `platosim.starquery`. Please check that you have pulled the latest version of the develop branch (and merged it of course). Remember after each update you need to run the `setup.sh` script to copy the PLATOnium toolkit scripts to your Conda environment.

If you still have issues, please provide the info from these commands: `git describe --tag` and `git log` (only the latest log message).

**Comment by AstroSaad** [comment]
I've git pulled the develop branch and I re-build as per the branching strategy instructions.

`git describe --tag` returns `3.6.0-202-g4c2967e2`

The latest log message from `git log` is: 
```
commit 4c2967e2a5a8e38ebd88567dd37e3a99620f7a2a (HEAD -> develop, origin/develop, origin/HEAD)
Merge: 55a970f6 efebbade
Author: Nicholas Jannsen <36379445+nicholasjannsen@users.noreply.github.com>
Date:   Sun Oct 8 14:44:58 2023 +0200

    Merge pull request #896 from nicholasjannsen/develop
    
    Solves issue #306. New script to create PLATO FoV catalogues
```

**Comment by nicholasjannsen** [comment]
Hi again, I think the reason why you have this issue is because Conda is looking for `picsim` in the folder `/home/ubuntu/anaconda3/bin` which is the "base" directory. That could mean that the symbolic link to `picsim` is simply wrong. If you followed the tutorial for setting up PLATOnium all of the symbolic links to the scripts should be stored in your Conda environment. E.g. say that I create a Conda environment called `platosim`:

```
conda create -n platosim python=3.9
conda activate platosim
```
then I make sure remove the `poetry.lock` file in the **PlatoSim3** directory and use Poetry for the package management:

```
poetry install --with platonium
``` 

Next we setup our project by making the `$PLATO_PROJECT_HOME` and the `$PLATO_WORKDIR` globally know and add the python scripts to our Conda environment. This is done with:

```
./setup.sh <path/to/plato_wordir>
```
I remember you had problems with this setup on Mac, but I guess you are using Ubuntu now given the above path (hence it should work flawlessly). Now you can check where the symbolic links are stored, e.g.:

```
which picsim
```
following the above steps should give you something like:

```
/home/ubuntu/anaconda3/envs/platosim/picsim
```
Thus, we now have `picsim` stored in the correct folder `envs/platosim` and not within the base `bin` of Anaconda. I hope this help. 

Could it be that you didn't have your Conda environment activated when you ran the `setup.sh` script?

**Comment by AstroSaad** [comment]
I hadn't run the ./setup.sh script. I think, when I first tried to run it a month or so ago, it didn't really work properly (this might have been when I was still trying to run platonium on Mac).

I've pulled the latest branch and have followed the steps as you've laid out. The `which picsim` command returns

`/home/ubuntu/anaconda3/envs/testplato/bin/picsim
`
So I think everything is fine now.

**Comment by nicholasjannsen** [comment]
Great that it works. I have meanwhile tested the installation using Poetry and both with (Conda) Python v. 3.8, 3.9, and 3.10 as successful installation is maintained.
