### ISSUE TITLE
Higher resolution of the subfield matrix

### ISSUE THREAD

**Issue by BertoltLang** [IvS-KULeuven/PlatoSim3#95]
for a better comparability of the different simulation software used by us, a higher resolution of the subpixel images would be much appreciated. Is there a way to use PlatoSim with 1024 or even 2048 subpixels?

**Comment by JorisDeRidder** [comment]
Using PlatoSim with subfields of 9x9 (e.g. as used in the fgs.py script) with 1024x1024 subpixels per pixel does work on my Macbook Pro laptop, albeit slow.

**Comment by BertoltLang** [comment]
That's correct, but only with a gaussian PSF. If I want to use the "FromFile" option in the PSF section of the imputfgs.yaml, an error message informs me,  that: "rebinning currently only implemented to smaller dimensions.", when I run a simulation with 256 subpixels or more.
I suppose, a different, larger PSF model is needed to make this possible.

**Comment by JorisDeRidder** [comment]
OK, now I understand better. The error message given by PlatoSim is indeed because you are trying to request a higher resolution than is given in the psf.hdf5 file. 
I see two possibilities: 1) interpolating the PSFs in psf.hdf5, or 2) asking Demetrio if it's possible to  compute PSFs with 1024x1024 subpixels/pixel. Which one is right for you, depends a bit on your application. Also, with interpolating, what interpolation method is required for your purposes? I suspect a simple bilinear interpolation may not be enough, as you will probably still see the jumps in the astrometry.
We can help of course, but we need more information on what approach is required for your application.

**Comment by BertoltLang** [comment]
Thank you for your input! I interpolated the PSF myself to fit our purposes. I close the issue.
