### ISSUE TITLE
Imagettes not generating properly

### ISSUE THREAD

**Issue by bowl-sa** [IvS-KULeuven/PlatoSim3#983]
Hello all,

I am trying to simulate a star at a given RA and DEC on the F-CAMs, but the imagettes I generate seem to be only background.

`subfieldSizeX = 20
subfieldSizeY = 20

raCenter = 92.2426
decCenter = -36.7977
ccdCode, xCCDpixel, yCCDpixel = rf.skyToPixelCoordinates(sim, raCenter, decCenter, normal=True)

sim.setSubfieldAroundSkyCoordinates(raCenter, decCenter, subfieldSizeX, subfieldSizeY, normal=True)

row = np.array([yCCDpixel])
col = np.array([xCCDpixel]) 
mag = np.array([8.5])
starID = [1]

starcatFile = outputDir + "/starcat_test_1.txt"
sim.createStarCatalogFileFromPixelCoordinates(row, col, mag, starID, starcatFile)

simfile = sim.run(removeOutputFile=True)
fig, ax = simfile.showImage(imageNr=False,  imgScale="percentile", clip=1,  
                            figsize=(7,7), fontSize=20, useTitle=False,
                            showStarPositions=True, showStarIDs=False,
                            colorMap="cubehelix", colorBar=True, showGrid=True);
`
Output:
![Capture](https://github.com/IvS-KULeuven/PlatoSim3/assets/148346259/eefeedc3-dd20-4178-8fd7-115ee41e64ee)

When I run setSubfieldAroundSkyCoordinates, it returns True, which to my understanding means the star is falling on one of the CCDs, so I don't know why PlatoSim is unable to see it. 

Thanks for your help.

**Comment by Dries-Seynaeve** [comment]
Hi, 

I see that for the function `setSubfieldAroundSkyCoordinates`  your last argument is `normal=True`. If you want to set the subfield for Fast Cameras, this should be set to `False`. Maybe this might explain the issue. 

If this does not fix the issue, could you share the whole python code or the input file for the simulation to create the plot?

Kind regards 
Dries

**Comment by bowl-sa** [comment]
Hi Dries,

That didn't seem to work. I've attached a zip archive containing the script and the input file I used.

Thank you,
Sam
[imagette.zip](https://github.com/IvS-KULeuven/PlatoSim3/files/15334372/imagette.zip)

**Comment by Dries-Seynaeve** [comment]
Hi, thanks a lot for this. 

So I think there were two main issues here. 
Firstly, you also used the `skyToPixelCoordinates` function with the wrong argument (`normal=True)`. 
Secondly, the input angles for  `skyToPixelCoordinates` and `setSubfieldAroundSkyCoordinatesshould` should be given in radians, not in degrees.

The use of the argument `normal=False` seems a bit counter intuitive since these values could (and probably should) always be derived from the Simulation object that is used. To avoid issues like this, I opted to deprecate the use of this argument. It is still possible to use them, but a warning will be generated. So to try this again, I would advise to update PlatoSim to the latest version. 

I'll include a part of your code with these changes implement, let me know if this works for you. You might have to update PlatoSim to the latest version. 

[GitHubError.py.txt](https://github.com/IvS-KULeuven/PlatoSim3/files/15351427/GitHubError.py.txt)

**Comment by bowl-sa** [comment]
Hi Dries,

Converting my coordinates to radians did the trick. Everything seems to be working now.

Thank you,
Sam
